### ISSUE TITLE
Tailwind randomly fails using Elixir on Ubuntu 22.04 and esbuild.

### ISSUE THREAD

**Issue by severian1778** [tailwindlabs/tailwindcss#10084]
I would like to give context  but I have no idea what this error even means or how to even begin diagnosing it.   Seems like a bug.

TypeError: Cannot read properties of undefined (reading 'insertAfter')
    at Root.after (/snapshot/tailwindcss/node_modules/postcss/lib/node.js:161:17)
    at partitionRules (/snapshot/tailwindcss/lib/lib/partitionApplyAtRules.js:47:18)
    at /snapshot/tailwindcss/lib/lib/partitionApplyAtRules.js:54:9
    at /snapshot/tailwindcss/lib/processTailwindFeatures.js:32:46
    at Object.Once (/snapshot/tailwindcss/lib/cli/build/plugin.js:251:19)
    at LazyResult.runOnRoot (/snapshot/tailwindcss/node_modules/postcss/lib/lazy-result.js:337:23)
    at LazyResult.runAsync (/snapshot/tailwindcss/node_modules/postcss/lib/lazy-result.js:393:26)
    at async build (/snapshot/tailwindcss/lib/cli/build/index.js:42:9)

**Comment by adamwathan** [comment]
Hey! I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction — a [Tailwind Play](https://play.tailwindcss.com) if the issue can be reproduced there, or a GitHub repository where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
