### ISSUE TITLE
tauri integration fails

### ISSUE THREAD

**Issue by thinkrapido** [tailwindlabs/tailwindcss#10081]
### Describe the bug

I think, the problem is, because the processing mechanism of postcss.

I followed the installation instructions of tailwindcss from the webpage https://tailwindcss.com/docs/guides/sveltekit

I get

```
[vite] Internal server error: [postcss] /<abs path to project>/src/routes/+page.svelte?svelte&type=style&lang.css:1:1: Unknown word
  Plugin: vite:css
  File: /<abs path to project>/src/routes/+page.svelte?svelte&type=style&lang.css:1:1
  1  |  <script>
     |   ^
  2  |    import Greet from "$lib/Greet.svelte";
  3  |  </script>

```

### Reproduction

1. Blank install of tauri with svelte & Typescript
2. Adding tailwind described on webpage https://tailwindcss.com/docs/guides/sveltekit

### Expected behavior

We are having here an absolute path from the filesystem.
I suppose, postcss needs an url to attach url parameters on it to parse the css

?svelte&type=style&lang.css:1:1

### Platform and versions

I think any

### Stack trace

```shell
at Input.error (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/input.js:148:16)
      at Parser.unknownWord (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/parser.js:540:22)
      at Parser.other (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/parser.js:164:12)
      at Parser.parse (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/parser.js:72:16)
      at parse (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/parse.js:11:12)
      at new LazyResult (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/lazy-result.js:133:16)
      at Processor.process (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/processor.js:28:14)
      at compileCSS (file:///home/jbc/Work/indi/indi-desktop/node_modules/vite/dist/node/chunks/dep-2285ba4f.js:37647:14)
      at async TransformContext.transform (file:///home/jbc/Work/indi/indi-desktop/node_modules/vite/dist/node/chunks/dep-2285ba4f.js:37121:56)
      at async Object.transform (file:///home/jbc/Work/indi/indi-desktop/node_modules/vite/dist/node/chunks/dep-2285ba4f.js:42569:30)
```

**Comment by thinkrapido** [comment]
Original Post: https://github.com/tauri-apps/tauri/issues/5839

**Comment by thecrypticace** [comment]
At a first glance this appears to be a processing issue where a script block is picked up as a style block. That seems quite strange.

I've tested Tailwind CSS with Svelte Kit _very_ recently (within the last 7 days) and things were working fine. There's a chance it'd have something specific to do with the combination of the way Svelte, Tauri, and PostCSS are wired together.

I'll take look in the morning and see what I can figure out.

**Comment by thecrypticace** [comment]
@thinkrapido Can you provide a repo I can clone that reproduces this issue? I set up a new Tauri project from scratch with Svelte and followed our instructions and things appear to work correctly.

**Comment by thinkrapido** [comment]
The project is at: https://github.com/thinkrapido/tauri-tailwindcss-bug

I'm using nix to power the app. See `shell.nix`.

For windows I have to solve this problem first : https://github.com/tauri-apps/tauri/issues/5845

**Comment by thinkrapido** [comment]
This is a nix specific problem.
I tested it on Windows and it works fine.
Any help for this?
If not, then we can close this issue.

**Comment by thinkrapido** [comment]
Sorry, this is not a nix specific problem.
I can replicate it with ubuntu 22.04.

I further inverstigated it and I created a clean installation of tauri.
This can show up its app.
After I integrated tailwindcss and applied `yarn tauri dev` this error appeared again.
Then I created a build and tauri creates a in the cargo release folder an executable.
Starting this works with tailwindcss.

This is strange and it lets me think about how vite runs in development mode.
Something strange happens here.

Where can I find more information about vite and its dev mode processing?

**Comment by thinkrapido** [comment]
```
rm -rf src-tauri/target
rm -rf .svelte-kit
yarn tauri dev
fixes it
```

!!!SOLVED!!!

**Comment by ItsEthra** [comment]
Hello, I'm having the same issue. I created blank tauri project with yarn, svelte, typescript and followed steps to add tailwindcss just as you described and I still have the same issue. Removing `src-tauri/target` didn't help and I also do not have the `.svelte-kit` directory. Any help?
```
1:40:26 PM [vite] Internal server error: [postcss] /home/ethra/yclass/src/App.svelte?svelte&type=style&lang.css:39:1: Unknown word
  Plugin: vite:css
  File: /home/ethra/yclass/src/App.svelte?svelte&type=style&lang.css:39:1
  37 |      filter: drop-shadow(0 0 2em #ff3e00);
  38 |    }
  39 |  </style>
     |   ^
      at Input.error (/home/ethra/yclass/node_modules/postcss/lib/input.js:106:16)
      at Parser.unknownWord (/home/ethra/yclass/node_modules/postcss/lib/parser.js:594:22)
      at Parser.other (/home/ethra/yclass/node_modules/postcss/lib/parser.js:436:12)
      at Parser.parse (/home/ethra/yclass/node_modules/postcss/lib/parser.js:471:16)
      at parse (/home/ethra/yclass/node_modules/postcss/lib/parse.js:11:12)
      at new LazyResult (/home/ethra/yclass/node_modules/postcss/lib/lazy-result.js:133:16)
      at Processor.process (/home/ethra/yclass/node_modules/postcss/lib/processor.js:53:14)
      at compileCSS (file:///home/ethra/yclass/node_modules/vite/dist/node/chunks/dep-df561101.js:38868:63)
      at async TransformContext.transform (file:///home/ethra/yclass/node_modules/vite/dist/node/chunks/dep-df561101.js:38266:56
```

**Comment by evallen** [comment]
I'm also having the same issue. Did you ever figure it out?

**Comment by thinkrapido** [comment]
Right mouse, Reload page, solves it. And I still have this issue when opening the app the first time with `yarn tauri dev`

**Comment by Pandananana** [comment]
I had the same issue after running the create-tauri-app for Tauri V2.

I fixed it by modifying the style tag in the offending svelte file and adding css as the language: 

`<style lang="css">`

Then it worked, also when opening the app for the first time.

**Comment by yueduz** [comment]
I have the same problem when I open it from npm run tauri dev.
I run npm run dev and open http://localhost:1420/ from chrome without any problem.
