### ISSUE TITLE
`[postcss] Cannot read properties of undefined (reading 'config')` with the new Tailwind typescript config file

### ISSUE THREAD

**Issue by frederikhors** [tailwindlabs/tailwindcss#10968]
Using the new (from 3.3) `tailwind.config.ts` typescript file doesn't work with postcss given the below `postcss.config.cjs` file:

```cjs
module.exports = {
  plugins: [
    require("tailwindcss"),

    require("autoprefixer"),

    require("cssnano")({ preset: "default" }),
  ],
};
```

The error:

```
[vite] Internal server error: [postcss] Cannot read properties of undefined (reading 'config')
  Plugin: vite:css
      at getTailwindConfig (C:\project\node_modules\tailwindcss\lib\lib\setupTrackingContext.js:84:63)
      at C:\project\node_modules\tailwindcss\lib\lib\setupTrackingContext.js:96:92
      at C:\project\node_modules\tailwindcss\lib\processTailwindFeatures.js:46:11
      at plugins (C:\project\node_modules\tailwindcss\lib\index.js:38:63)
      at LazyResult.runOnRoot (C:\project\node_modules\postcss\lib\lazy-result.js:339:16)
      at LazyResult.runAsync (C:\project\node_modules\postcss\lib\lazy-result.js:393:26)
      at async compileCSS (file:///C:/project/node_modules/vite/dist/node/chunks/dep-79892de8.js:38354:25)
      at async TransformContext.transform (file:///C:/project/node_modules/vite/dist/node/chunks/dep-79892de8.js:37810:56)
      at async Object.transform (file:///C:/project/node_modules/vite/dist/node/chunks/dep-79892de8.js:43387:30)
      at async loadAndTransform (file:///C:/project/node_modules/vite/dist/node/chunks/dep-79892de8.js:41105:29) (x2)
```

I opened https://github.com/postcss/postcss/issues/1829 but as you can see they told me to open it here.

**Comment by frederikhors** [comment]
Sorry, my bad.

**Comment by Ioome** [comment]
How do you solve,

**Comment by Ioome** [comment]
Similarly, I also met

**Comment by Ioome** [comment]
😐
