### ISSUE TITLE
Standalone CLI build fails with first-party plugin in config

### ISSUE THREAD

**Issue by shoutbc** [tailwindlabs/tailwindcss#12374]
**What version of Tailwind CSS are you using?**

tailwindcss v3.3.5

**What build tool (or framework if it abstracts the build tool) are you using?**

Standalone CLI (https://tailwindcss.com/blog/standalone-cli)

**What version of Node.js are you using?**

N/A

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction URL**

Not Needed

**Describe your issue**

Standalone CLI throws error after adding first party plugin to the config (@tailwindcss/forms). 

Config:
/** @type {import('tailwindcss').Config} */

module.exports = {
  content: [
    "../resources/**/*.blade.php",
  ],
  plugins: [
    require('@tailwindcss/forms'),
  ]
}

Error:
Rebuilding...
Error: Cannot find module '@tailwindcss/forms'
Require /public/tailwind.config.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at _resolve (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:250334)
    at jiti (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:252917)
    at /home/eduquiz-5wyxc/staging.eduquiz.ca/public/tailwind.config.js:8:5
    at evalModule (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:255614)
    at jiti (/snapshot/tailwindcss/node_modules/jiti/dist/jiti.js:1:253542)
    at /snapshot/tailwindcss/lib/lib/load-config.js:37:30
    at loadConfig (/snapshot/tailwindcss/lib/lib/load-config.js:39:6) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/[website]/public/tailwind.config.js'
  ]
}

**Comment by thecrypticace** [comment]
Notes for me tomorrow:
- In a standard CJS config this works
- If the config file is TypeScript, ESM, or otherwise has to be compiled by Jiti this error happens.
