### ISSUE TITLE
v4 alpha does not work on Stackblitz

### ISSUE THREAD

**Issue by jcbhmr** [tailwindlabs/tailwindcss#13133]
**What version of Tailwind CSS are you using?**

4.0.0-alpha.6

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite 5.1.5

**What version of Node.js are you using?**

v18.18.0

**What browser are you using?**

Chrome

**What operating system are you using?**

StackBlitz

**Reproduction URL**

https://stackblitz.com/edit/vitejs-vite-bhcbjy?file=vite.config.js&terminal=dev

A Tailwind Play link or public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways.

A reproduction is **required** when filing an issue — any issue opened without a reproduction will be closed and you'll be asked to create a new issue that includes a reproduction. We're a small team and we can't keep up with the volume of issues we receive if we need to reproduce each issue from scratch ourselves.

**Describe your issue**

```sh
~/projects/vitejs-vite-bhcbjy 3s
❯ npm run dev

> vite-starter@0.0.0 dev
> vite

failed to load config from /home/projects/vitejs-vite-bhcbjy/vite.config.js
error when starting dev server:
Error: Cannot load native addon because loading addons is disabled: /home/projects/vitejs-vite-bhcbjy/node_modules/@tailwindcss/oxide-linux-x64-musl/tailwindcss-oxide.linux-x64-musl.node
    at process.dlopen (https://vitejsvitebhcbjy-emlm.w-credentialless-staticblitz.com/blitz.8e1c3ef8.js:352:49789)
    at Module._extensions..node (https://vitejsvitebhcbjy-emlm.w-credentialless-staticblitz.com/blitz.8e1c3ef8.js:54:15934)
    at Module.load (https://vitejsvitebhcbjy-emlm.w-credentialless-staticblitz.com/blitz.8e1c3ef8.js:54:13457)
    at Module._load (https://vitejsvitebhcbjy-emlm.w-credentialless-staticblitz.com/blitz.8e1c3ef8.js:54:10535)
    at Module.require (https://vitejsvitebhcbjy-emlm.w-credentialless-staticblitz.com/blitz.8e1c3ef8.js:54:13775)
    at i (https://vitejsvitebhcbjy-emlm.w-credentialless-staticblitz.com/blitz.8e1c3ef8.js:98:2198)
    at _0x271448 (https://vitejsvitebhcbjy-emlm.w-credentialless-staticblitz.com/blitz.8e1c3ef8.js:352:193624)
    at Object.eval (file:///home/projects/vitejs-vite-bhcbjy/node_modules/@tailwindcss/oxide/index.js:177:31)
    at Object.function (https://vitejsvitebhcbjy-emlm.w-credentialless-staticblitz.com/blitz.8e1c3ef8.js:352:194402)
    at Module._compile (https://vitejsvitebhcbjy-emlm.w-credentialless-staticblitz.com/blitz.8e1c3ef8.js:54:14871)
```

**Comment by adamwathan** [comment]
Just a note for future us, looks like this is because StackBlitz doesn't support loading native modules:

https://developer.stackblitz.com/platform/webcontainers/troubleshooting-webcontainers#cannot-load-native-addon

Not sure if there's anything we can do to make this work, maybe we can compile a WASM version and somehow have that get installed in these environments? Will leave this open to investigate for a bit but might ultimately not be something we can solve.

**Comment by devongovett** [comment]
For lightning css we have a separate WASM package (`lightningcss-wasm`), which shims the exact API of the node package. I worked with the stackblitz team to get this automatically aliased in their environment so whenever someone imports `lightningcss` it actually imports `lightningcss-wasm` inside stackblitz. In order to reuse the `napi` code in WASM, I wrote [napi-wasm](https://github.com/devongovett/napi-wasm), which shims the napi API in browsers. Here's the [source](https://github.com/parcel-bundler/lightningcss/tree/master/wasm) for the wasm package in lightningcss in case it helps.

**Comment by d3lm** [comment]
Hey 👋 Thanks for pinging me @devongovett 🙏

@adamwathan Indeed, you cannot load native addons in WebContainer because arbitrary native binaries cannot be executed in the browser. Therefore, for this to work it requires a Wasm package. Here's a good example for a setup that I'd suggest: https://github.com/Brooooooklyn/Image/blob/95c248a04fa0b748a280be0d9936be18d744221f/packages/binding/index.js#L338-L355.

Essentially, you need to define another platform-specific dependency that targets `wasm32`. For that package you have to set the `cpu` to `wasm32` (see [this](https://github.com/Brooooooklyn/Image/blob/95c248a04fa0b748a280be0d9936be18d744221f/packages/binding/npm/wasm32-wasi/package.json#L4-L6) example). This means that if you run `npm install` locally, it would just install the dependency that matches your local architecture and in WebContainer it would download and install the Wasm package because we are going to roll out a change to WebContainer's architecture and flip it from `x64` to `wasm32`. This is the most ideal setup and something I'd also like to change for `lightningcss` and `parcel-watcher` (cc @devongovett).

What we have done for `lightningcss` is to use a Wasm package that is registered as a "polyfill" on our side which means that when you install `lightningcss` it will auto-magically install the Wasm package. You can try that out on StackBlitz and inspect `node_modules`. However, given that we are about to change the architecture for WebContainer, like I said, I'd recommend the former approach now. For the polyfill route to work, it really has to be an exact drop-in replacement and any additional dependencies have to become `bundledDependencies` as those won't be seen by the package manager.

I'd recommend taking a look at [napi-rs](https://github.com/napi-rs/napi-rs) or [napi-wasm](https://github.com/devongovett/napi-wasm).

Let me know if I can help any further. Happy to collaborate if you need more input or direction. It's important to us to ensure that tailwindcss continues to work in WebContainer.

**Comment by RobinMalfait** [comment]
Hey!

I think the better solution to use Tailwind CSS in environments like StackBlitz might be to use the CDN directly. This is just an unpkg.com link (or any CDN provider that pulls from npm). Setup: https://tailwindcss.com/docs/installation/play-cdn

For real projects, you should still setup Tailwind CSS properly.

We could still try to setup a wasm build to make this all work, but a solution that works today is the CDN.

Going to close this issue for now since I don't think there is a lot we can/should do, and I think the CDN is a good solution for these environments.

We can re-open this if we really want to push the wasm build though.

**Comment by laktek** [comment]
A WASM build would also be great for making Tailwind V4 work with Deno compiled binaries (currently, NAPI builds of Oxide doesn't work when included in a [Deno-compiled binary](https://github.com/denoland/deno/issues/23266))

**Comment by diegohaz** [comment]
I often use StackBlitz to quickly launch projects directly from GitHub using the [Project URL](https://developer.stackblitz.com/guides/integration/open-from-github#project-url). It would be awesome if Tailwind was supported in this case.

**Comment by SeanCassiere** [comment]
> I often use StackBlitz to quickly launch projects directly from GitHub using the [Project URL](https://developer.stackblitz.com/guides/integration/open-from-github#project-url). It would be awesome if Tailwind was supported in this case.

We'll likely be locking the dependencies to whatever the latest version of Tailwind v3 is, for our examples in TanStack Router. 

This may just be the path for any other OSS maintainers that have examples/sandboxes that are hosted on a stackblitz playground.

**Comment by phaux** [comment]
Another option is to switch to unocss after it gets tailwind 4 support: https://github.com/unocss/unocss/issues/4411

**Comment by diegohaz** [comment]
> I think the better solution to use Tailwind CSS in environments like StackBlitz might be to use the CDN directly. This is just an unpkg.com link (or any CDN provider that pulls from npm). Setup: https://tailwindcss.com/docs/installation/play-cdn

Hi @RobinMalfait! Does the CDN version support plugins (either `@plugin` or `@import`)? If so, what's the recommended way to add them?

**Comment by Powerplex** [comment]
In v3, we used to share a stackblitz to our users to reproduce bugs easily. We provide a tailwind based design system with custom themes (we reset some namespaces, such as colors, spacing, etc with our own semantic). This is no longer possible with v4 unless tailwind support WASM like @laktek said above.

**Comment by huntabyte** [comment]
> Going to close this issue for now since I don't think there is a lot we can/should do, and I think the CDN is a good solution for these environments.

I totally get that a wasm build might be a bigger lift and that the CDN is a workable solution for some cases.

That said, I think there’s still a bit of a gap for library maintainers who rely heavily on StackBlitz and web containers for repros, as well as all of the Bolt.new users. Vite-based setups are dominant, and guidance being to switch to the PlayCDN doesn't feel right. 

It’d be amazing if there was a smoother path forward that didn’t require rethinking the setup just for these environments, especially since StackBlitz offered help to make this happen.

Doesn't closing the issue reduce the chances someone from the community may help resolve this?

**Comment by ascorbic** [comment]
I have to agree with @huntabyte. Using the CDN is not a valid option for many of us who use Stackblitz for bug reproductions. I am an Astro maintainer, and like many other OSS projects we use Stackblitz to allow users to create bug reproductions. The lack of WASM support means that users can't do this with any issue that involves Tailwind. Loading from the CDN isn't an option, because it would not be testing the same code. Our users have had several issues with Tailwind 4, and this has prevented our users from providing working reproductions of these issues, making it harder for us to fix the issues. This issue should be reopened, because it is not fixed and the CDN option is not a valid workaround for many of the most common use cases.

**Comment by EricSimons** [comment]
Hi all- cofounder of StackBlitz/Bolt here! We'd love to help in any way here, whether providing guidance, funding work on this, etc. As others have noted Wasm support for Tailwind v4 is not just an issue for StackBlitz/Bolt users but also other envs that may not be able to load non-Wasm addons (Deno, Node.js when security flags are set, etc).

@adamwathan what would be the best way to proceed here?

**Comment by samdenty** [comment]
WASM is a massive investment for anyone trying to ship CLIs / apps, WASI is still highly experimental and not feature complete yet. Building high performance native software with bindings to system-level interfaces just works the best on targets it’s designed for like ARM, x86 etc.

I think any IDE with a high amount of users should aim to provide support for 100% of the core software components that customers expect to use in their apps. I really don’t think it should fall on maintainers to have to try to target, develop, support, invest & maintain a novel execution method for a specific subset of users. It should be a core function of the platform to support the de-facto form factors the software their target audience wants to use.

**Comment by ascorbic** [comment]
@samdenty I mean, that would be great if you could, but how would you do it? Are you suggesting that you would support native Arm or x86 extensions in the browser, or would it be a toolchain that library authors would need to use to target the WebContainer architecture?

**Comment by devongovett** [comment]
https://github.com/yomaytk/elfconv 😄

**Comment by samdenty** [comment]
Lots of ways to run native code, whether on a server, emulated etc. I think the platform should have the responsibility of ensuring it's compatible with all software, ie. bun doesn't expect maintainers to update their apps if stuff doesn't work - they build compatibility for it

**Comment by EricSimons** [comment]
Update: @adamwathan and I are in touch & getting our teams connected to make this happen! Sounds like we might be able to get this started as soon as next week 🙌 Will circle back with updates as we progress

**Comment by Powerplex** [comment]
Hello, someone sent me this earlier today: https://x.com/boltdotnew/status/1912149005674615272?s=61

So I tried to update my stackblitz to work with my design system (which is using Tailwind), and unfortunately it seems the `@source` directive of the v4 is unable to parse the `node_modules` directory. I need to be able to parse `./node_modules/@spark-ui` in my case, as it is my component library. Fun fact: the `@import` directive works when targetting the `node_modules`, it is only `@source` that does not work.

- The local tailwind v4 config now works for the most part ✅ 
- But I'm unable to parse my components located in `node_modules` 🔴 

It is already better (thanks @adamwathan), but we are using Stackblitz to provide a bug-reproduction environement for our users, and they can't use it still because of that.

Any idea why ? Should I open a separate issue for this ?

Here is a minimal stackblitz with the issue: https://stackblitz.com/edit/stackblitz-starters-wpsedvj7?file=app%2Fcontent.tsx

**Comment by WangJM001** [comment]
> Hello, someone sent me this earlier today: https://x.com/boltdotnew/status/1912149005674615272?s=61
> 
> Thank you very much for the hard work 👏
> 
> I still have one blocking issue: I tried to update my stackblitz to work with my design system (which is using Tailwind), and unfortunately it seems the `@source` directive of the v4 is unable to parse the `node_modules` directory (only in stackblitz). I need to be able to parse `./node_modules/@spark-ui` in my case, as it is my component library. Fun fact: the `@import` directive works when targetting the `node_modules`, it is only `@source` that does not work.
> 
> * The local tailwind v4 config now works for the most part ✅
> * But I'm unable to parse my components located in `node_modules` 🔴
> 
> It is already better (thanks [@adamwathan](https://github.com/adamwathan)), but we are using Stackblitz to provide a bug-reproduction environement for our users, and they can't use it still because of that.
> 
> Any idea why ? Should I open a separate issue for this ?
> 
> Here is a minimal stackblitz with the issue: https://stackblitz.com/edit/stackblitz-starters-wpsedvj7?file=app%2Fcontent.tsx

+1, I have the same issue.
