### ISSUE TITLE
[v4] Cannot read properties of null (reading 'edgesOut')

### ISSUE THREAD

**Issue by nam-co** [tailwindlabs/tailwindcss#13139]
Hello, I tried npm install tailwindcss@next @tailwindcss/cli@next but I always get 

Cannot read properties of null (reading 'edgesOut')

and now, v3.x is not working, rebuilding gets stuck and after a while, it outputs this error:

Rebuilding...
Error: ETIMEDOUT: connection timed out, read
    at Object.readFileSync (node:fs:455:20)
    at Object.readContentPaths (/Users/macbookpro/Library/Mobile Documents/com~apple~CloudDocs/PROYECTS/SHOWPAGE/Showpage-backend/node_modules/tailwindcss/lib/cli/build/plugin.js:177:42)
    at Object.getContext (/Users/macbookpro/Library/Mobile Documents/com~apple~CloudDocs/PROYECTS/SHOWPAGE/Showpage-backend/node_modules/tailwindcss/lib/cli/build/plugin.js:220:31)
    at /Users/macbookpro/Library/Mobile Documents/com~apple~CloudDocs/PROYECTS/SHOWPAGE/Showpage-backend/node_modules/tailwindcss/lib/cli/build/plugin.js:254:38
    at /Users/macbookpro/Library/Mobile Documents/com~apple~CloudDocs/PROYECTS/SHOWPAGE/Showpage-backend/node_modules/tailwindcss/lib/processTailwindFeatures.js:48:11
    at Object.Once (/Users/macbookpro/Library/Mobile Documents/com~apple~CloudDocs/PROYECTS/SHOWPAGE/Showpage-backend/node_modules/tailwindcss/lib/cli/build/plugin.js:262:19)
    at LazyResult.runOnRoot (/Users/macbookpro/Library/Mobile Documents/com~apple~CloudDocs/PROYECTS/SHOWPAGE/Showpage-backend/node_modules/postcss/lib/lazy-result.js:327:23)
    at LazyResult.runAsync (/Users/macbookpro/Library/Mobile Documents/com~apple~CloudDocs/PROYECTS/SHOWPAGE/Showpage-backend/node_modules/postcss/lib/lazy-result.js:258:26)
    at async Object.watch (/Users/macbookpro/Library/Mobile Documents/com~apple~CloudDocs/PROYECTS/SHOWPAGE/Showpage-backend/node_modules/tailwindcss/lib/cli/build/plugin.js:375:13)
    at async build (/Users/macbookpro/Library/Mobile Documents/com~apple~CloudDocs/PROYECTS/SHOWPAGE/Showpage-backend/node_modules/tailwindcss/lib/cli/build/index.js:47:9) {
  errno: -60,
  code: 'ETIMEDOUT',
  syscall: 'read'
}

I tried uninstalling both v3 and v4 but I get null edgesOut error

Any ideas? appreciate any help

macOS Sonoma
npm: 10.5.0
node: 21.7.0

**Comment by RobinMalfait** [comment]
Hey!

Make sure you complete remove the `node_modules` folder and if you are using any tools (such as Next.js) make sure to also drop the caches (e.g.: remove the `.next` folder).

Can you provide a minimal reproduction repo so that we can take a look? Hard to guess what's going on based on the stack trace alone.

**Comment by adamwathan** [comment]
Hey! So this looks like a network time out because your project files are stored in iCloud, and the files were not available locally when running your build and the request to iCloud to fetch them timed out (maybe weren't connected to the internet?)

I'd just give it a shot again while connected to the internet, I bet everything will work then. Personally would recommend keeping projects outside of iCloud because of this sort of thing, or configure things to make sure it's always keeping a copy of the files locally if possible.

**Comment by nam-co** [comment]
@adamwathan and @RobinMalfait thanks you for the response, I ended up removing and reinstalling and it started working, also noted that the vendor folder was not in the HD, strange because I "composer update" a lot, this should happen after 30 days of inactivity (I think), and yes it's a bad habit I have of putting all work in iCloud, I think it also makes it slower, that is something I have to fix and commit/push more just to keep it safe, thanks, good luck with V4 -> hope there must be a way to include the vendor/ folder in content 🙏
