### ISSUE TITLE
[v4] `package.json` in `@tailwindcss/vite` is not standard.

### ISSUE THREAD

**Issue by blackcater** [tailwindlabs/tailwindcss#13216]
When I use `@tailwindcss/vite`@4 with `storybook`. It reported an error as bellow:

```
SB_CORE-SERVER_0007 (MainFileEvaluationError): Storybook couldn't evaluate your .storybook/main.ts file.

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /.../node_modules/@tailwindcss/vite/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:303:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:593:13)
    at resolveExports (node:internal/modules/cjs/loader:591:36)
    at Module._findPath (node:internal/modules/cjs/loader:668:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1130:27)
    at Module._resolveFilename (/Users/blackcater/Workspace/Codes/proj/staple/node_modules/esbuild-register/dist/node.js:4799:36)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/.storybook/main.ts:6:25)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

error: script "dev" exited with code 1
```

It seems like `esbuild` can't find `main` field in `package.json` from `@tailwindcss/vite` package.

**Comment by blackcater** [comment]
```typescript
const config: StorybookConfig = {
  stories: [/** stories */],
  addons: [/** addons */],
  framework: {
    name: '@storybook/react-vite',
    options: {},
  },
  viteFinal: async (config) => {
    config.plugins = config.plugins || []
    config.plugins.push((await import('@tailwindcss/vite')).default())

    return config
  },
}

export default config
```

Everything works fine.

Maybe `@tailwindcss/vite`'s `package.json` should more standard.

```json
{
  "main": "./dist/index.js", // CommonJS
  "module": "./dist/index.mjs", // ESM
  "types": "./dist/index.d.ts",
  "exports": {
    ".": {
      "types": "./dist/index.d.mts",
      "import": "./dist/index.mjs",
      "default": "./dist/index.js",
    },
    "./package.json": "./package.json"
  },
}
```

**Comment by thecrypticace** [comment]
What version of Node are you using? `main` and `module` are not required in Node as long as you have `exports` defined.

**Comment by blackcater** [comment]
> What version of Node are you using? `main` and `module` are not required in Node as long as you have `exports` defined.

```
node --version
v20.11.0
```

**Comment by KrisBraun** [comment]
@blackcater Could you share a repo with a reproduction?

**Comment by rostero1** [comment]
I got the same error when using this package with `bun` and `vite`.  I thought it was a `bun` thing, but Jarred replied back:

> The error is correct, “vite” is not there in exports.  So I think it’s a tailwind thing.

Error:

ERR_PACKAGE_PATH_NOT_EXPORTED No "exports" main defined in @tailwindcss/vite/package.json

**Comment by tounsoo** [comment]
I think this is the only post I found that mentions Storybook for v4, I am not able to get it working, can you share your setup?

**Comment by ekwoka** [comment]
> The error is correct, “vite” is not there in exports. So I think it’s a tailwind thing.

@rostero1 Unfortunately this seems like an incorrectly articulated statement, as if he was expecting `vite` to be an export of `tailwindcss` as opposed to `@tailwindcss/vite`

Don't know if he checked the right thing but said the wrong thing, or actually checked the wrong thing.

**Comment by adamwathan** [comment]
This issue is quite old without any recent activity so going to close this one right now, especially since it lacks a reproduction. If anyone is still having this issue, please don't hesitate to open a new issue that includes a reproduction and we can take a look 👍🏻

**Comment by codesculpture** [comment]
I came up with this issue, when i had imported normally using `import` statement

```javascript
import tailwindcss from "@tailwindcss/vite";

...
viteFinal: (config) =>  mergeConfig(config, plugins: [tailwindcss()])
```

And i changed to 

```javascript
async viteFinal(config) {
    const { default: tailwindcss } = await import("@tailwindcss/vite");
    return mergeConfig(config, plugins: [tailwindcss()])
}
```

**Comment by hernan-yadiel** [comment]
> I came up with this issue, when i had imported normally using `import` statement
> 
> import tailwindcss from "@tailwindcss/vite";
> 
> ...
> viteFinal: (config) =>  mergeConfig(config, plugins: [tailwindcss()])
> And i changed to below code, which no longers throw errors.
> 
> async viteFinal(config) {
>     const { default: tailwindcss } = await import("@tailwindcss/vite");
>     return mergeConfig(config, plugins: [tailwindcss()])
> }

This fixes it 👆. Btw, I think it's a Storybook issue.

**Comment by codesculpture** [comment]
> This fixes it 👆. Btw, I think it's a Storybook issue.

 If i add `require` key in `node_modules/@tailwindcss/vite/package.json`, it works even i import normally, such as 

```json
"exports": {
    ".": {
      "types": "./dist/index.d.mts",
      "import": "./dist/index.mjs",
      "require": "./dist/index.mjs"
    }
```

Am not sure why this works with `require` and not work without `require` while importing using import statement.

Someone said tailwind package.json should be standard somewhere in this issue.

**Comment by ekwoka** [comment]
Presumably, storybook is not using esm properly?

**Comment by robertoms99** [comment]
Use is because `node_modules/@storybook/core/dist/common/index.cjs:17557:11` (I suppose it s the loader for main.ts)  is a cjs file and is trying to `require('@tailwindcss/vite')` , the exports prop in `@tailwindcss/vite/package.json` doesnt expose a entry when a consumer import the package from cjs.

**Comment by GustavoHenriqueP** [comment]
> Issue is because `node_modules/@storybook/core/dist/common/index.cjs:17557:11` (I suppose it s the loader for main.ts) is a cjs file and is trying to `require('@tailwindcss/vite')` , the exports prop in `@tailwindcss/vite/package.json` doesnt expose a entry when a consumer import the package from cjs.

The problem persists. I believe that you are correct.
Even in Storybook 9.0.0, my console generates the following warning:

```bash
(node:56679) ExperimentalWarning: CommonJS module /home/user/www/project/.storybook/main.ts is loading ES Module /home/user/www/project/node_modules/.pnpm/vite@6.3.5_@types+node@22.15.21_jiti@2.4.2_lightningcss@1.30.1_yaml@2.7.1/node_modules/vite/dist/node/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time.
```

The warning is not related with TailwindCSS, but with the fact that Storybook is loading ES Modules with require().
