### ISSUE TITLE
SyntaxError: Unexpected token '?' 

### ISSUE THREAD

**Issue by JuanVargas** [tailwindlabs/tailwindcss#13878]
**What version of Tailwind CSS are you using?**

I am trying to use 3.4.4. which is the one that is installed when issuing the command  
npm install -D tailwindcss

**What build tool (or framework if it abstracts the build tool) are you using?** 

NONE. This error happens when I  try to install the framework under ubuntu 22.04.4 LTS

**What version of Node.js are you using?**

I am using v12.22.9

**What browser are you using?**

Chrome

**What operating system are you using?**

ubuntu 22.04.4 LTS

**Reproduction URL**

**Describe your issue**

When I issue the command

npx tailwindcss init

the install emits error 

mydir/.npm/_npx/bc7494899bbce1ca/node_modules/postcss-load-config/node_modules/lilconfig/src/index.js:163
	} = getOptions(name, options ?? {}, false);
	                              ^
SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/home/juan/.npm/_npx/bc7494899bbce1ca/node_modules/postcss-load-config/src/index.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
juan@JuanAsusBuntu:/drv3/hm3/code/tailwind$

**Comment by wongjn** [comment]
Seems like your Node.js version may be too old. Both Tailwind CSS and lilconfig suggest a Node.js version of at least 14.

**Comment by adamwathan** [comment]
Hey! Yep as @wongjn mentioned Tailwind requires at least Node v14 but I would recommend upgrading to Node v20, even Node v14 is so old that it is not maintained and doesn’t even receive security updates.

**Comment by JuanVargas** [comment]
Yes, updating to node v22.3 solved the problem.

Thank you
