### ISSUE TITLE
Cant Install tailwind with astro anymore...

### ISSUE THREAD

**Issue by erikdemarco** [tailwindlabs/tailwindcss#14291]
yesterday I successfully install astro with tailwind, using this exact steps from here:

`https://tailwindcss.com/docs/guides/astro`

Today I ant install anymore. It always shows:

```
7:35:13 PM [vite] Error when evaluating SSR module /home/Desktop/tmp/astro/my-project/astro.config.mjs: failed to import "@astrojs/tailwind"
|- SyntaxError: [vite] The requested module '@astrojs/tailwind' does not provide an export named 'tailwind'
    at analyzeImportedModDifference (file:///home/Desktop/tmp/astro/my-project/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:51946:15)
    at nodeImport (file:///home/Desktop/tmp/astro/my-project/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52958:5)
    at async ssrImport (file:///home/Desktop/tmp/astro/my-project/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52812:16)
    at async eval (/home/Desktop/tmp/astro/my-project/astro.config.mjs:4:31)
    at async instantiateModule (file:///home/Desktop/tmp/astro/my-project/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52870:5)

[astro] Unable to load your Astro config

[vite] The requested module '@astrojs/tailwind' does not provide an export named 'tailwind'
  Stack trace:
    at analyzeImportedModDifference (file:///home/Desktop/tmp/astro/my-project/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:51946:15)
    at async ssrImport (file:///home/Desktop/tmp/astro/my-project/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52812:16)
    at async instantiateModule (file:///home/Desktop/tmp/astro/my-project/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52870:5)
```

**Comment by egel557** [comment]
This worked for me:

Go to your `astro.config.mjs`. Then change the tailwind import from `import { tailwind } from "@astrojs/tailwind"` to `import tailwind from "@astrojs/tailwind"`.

**Comment by thecrypticace** [comment]
Thanks for reporting. It looks like this was earlier today by Astro: https://github.com/withastro/astro/pull/11872

Closing ✨

**Comment by SatyaRajAwasth1** [comment]
@egel557 @thecrypticace 

Seems like, Issue still exists out there. Faced the same with    

 ```
 "astro": "^5.1.7",

 "@astrojs/tailwind": "^5.1.4",
```
