### ISSUE TITLE
cli: Reading from stdin is broken in 4.0.0-alpha.25

### ISSUE THREAD

**Issue by bep** [tailwindlabs/tailwindcss#14521]
```
mkdir tailwindtest
cd tailwindtest
npm i @tailwindcss/cli@4.0.0-alpha.25 tailwindcss@4.0.0-alpha.25 --save-dev
echo "@import 'tailwindcss';" > foo.css

```
This works:

```
npx tailwindcss  -i foo.css -o bar.css
```

This fails:

```
npx tailwindcss  --input=- -o bar.css < foo.css
```

Output:

```
~/d/tailwindbug ❯❯❯ npx tailwindcss  --input=- -o bar.css < foo.css                                                                             main ✱ ◼
/Users/bep/dump/tailwindbug/node_modules/enhanced-resolve/lib/Resolver.js:564
			const error = new Error("Can't " + message);
			             ^

Error: Can't resolve 'tailwindcss' in '/Users/bep/dump'
    at finishWithoutResolve (/Users/bep/dump/tailwindbug/node_modules/enhanced-resolve/lib/Resolver.js:564:18)
    at /Users/bep/dump/tailwindbug/node_modules/enhanced-resolve/lib/Resolver.js:656:15
    at /Users/bep/dump/tailwindbug/node_modules/enhanced-resolve/lib/Resolver.js:718:5
    at eval (eval at create (/Users/bep/dump/tailwindbug/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/bep/dump/tailwindbug/node_modules/enhanced-resolve/lib/Resolver.js:718:5
    at eval (eval at create (/Users/bep/dump/tailwindbug/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/bep/dump/tailwindbug/node_modules/enhanced-resolve/lib/Resolver.js:718:5
    at eval (eval at create (/Users/bep/dump/tailwindbug/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/bep/dump/tailwindbug/node_modules/enhanced-resolve/lib/Resolver.js:718:5
    at eval (eval at create (/Users/bep/dump/tailwindbug/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1) {
  details: "resolve 'tailwindcss' in '/Users/bep/dump'\n" +
    '  Parsed request is a module\n' +
    '  No description file found in /Users/bep/dump or above\n' +
    '  resolve as module\n' +
    "    /Users/bep/dump/node_modules doesn't exist or is not a directory\n" +
    "    /Users/bep/node_modules doesn't exist or is not a directory\n" +
    "    /Users/node_modules doesn't exist or is not a directory\n" +
    "    /node_modules doesn't exist or is not a directory"
```

Downgrading to alpha 24 and it works:

```
npm i @tailwindcss/cli@4.0.0-alpha.24 tailwindcss@4.0.0-alpha.24 --save-dev
npx tailwindcss  --input=- -o bar.css < foo.css
```

**Comment by philipp-spiess** [comment]
@bep Thanks for the bug report! There's an issue in the base path it uses when configured with stdin input files. Will put out a fix shorty!

**Comment by philipp-spiess** [comment]
@bep Merged a fix for this now, it will be part of the next patch release. Thank you again!
