### ISSUE TITLE
[v4] Unable to use tailwind utilities in .vue `style` blocks

### ISSUE THREAD

**Issue by spaceemotion** [tailwindlabs/tailwindcss#15224]
**What version of Tailwind CSS are you using?**
v4-beta.3

**What build tool (or framework if it abstracts the build tool) are you using?**
Vite 6.0.1 (via Astro 5 beta)

**What version of Node.js are you using?**
v20

**What browser are you using?**
Chrome, Edge, Brave

**What operating system are you using?**
Windows, Linux

**Reproduction URL**

https://stackblitz.com/edit/vitejs-vite-hr6tpf?file=src%2FApp.vue

**Describe your issue**

I tried to make a small example above, but the error we are getting is in an Astro site of ours:

```vue
<style>
@utility tpp-button {
  @apply py-2 px-6 text-lg sm:text-xl md:text-2xl font-serif rounded-lg bg-black text-white inline-flex items-center justify-center transform-gpu will-change-transform;
  @apply [&:not(:disabled)]:hover:scale-105 transition-[transform] [&:not(:disabled)]:active:scale-95;
  @apply border-2 border-black disabled:border-dashed disabled:bg-white disabled:text-neutral-500 disabled:border-neutral-300;
  @apply touch-manipulation select-none;
  @apply focus-visible:ring-4 focus-visible:ring-black focus-visible:ring-offset-2;
  @apply ring-0 ring-offset-4 ring-offset-white ring-white;
}
</style>
```

When the page loads, it gives us the following error:
```
Error: Cannot apply unknown utility class: sm:text-xl
    at onInvalidCandidate (file:///home/spaceemotion/code/nc-website/novelcrafter/node_modules/.pnpm/tailwindcss@4.0.0-beta.3/node_modules/tailwindcss/dist/lib.mjs:12:107988)
    at Y (file:///home/spaceemotion/code/nc-website/novelcrafter/node_modules/.pnpm/tailwindcss@4.0.0-beta.3/node_modules/tailwindcss/dist/lib.mjs:12:105124)
    at file:///home/spaceemotion/code/nc-website/novelcrafter/node_modules/.pnpm/tailwindcss@4.0.0-beta.3/node_modules/tailwindcss/dist/lib.mjs:12:107952
    at D (file:///home/spaceemotion/code/nc-website/novelcrafter/node_modules/.pnpm/tailwindcss@4.0.0-beta.3/node_modules/tailwindcss/dist/lib.mjs:3:3654)
    at D (file:///home/spaceemotion/code/nc-website/novelcrafter/node_modules/.pnpm/tailwindcss@4.0.0-beta.3/node_modules/tailwindcss/dist/lib.mjs:3:3812)
    at D (file:///home/spaceemotion/code/nc-website/novelcrafter/node_modules/.pnpm/tailwindcss@4.0.0-beta.3/node_modules/tailwindcss/dist/lib.mjs:3:3604)
    at ge (file:///home/spaceemotion/code/nc-website/novelcrafter/node_modules/.pnpm/tailwindcss@4.0.0-beta.3/node_modules/tailwindcss/dist/lib.mjs:12:107678)
    at ur (file:///home/spaceemotion/code/nc-website/novelcrafter/node_modules/.pnpm/tailwindcss@4.0.0-beta.3/node_modules/tailwindcss/dist/lib.mjs:28:502)
    at async Uo (file:///home/spaceemotion/code/nc-website/novelcrafter/node_modules/.pnpm/tailwindcss@4.0.0-beta.3/node_modules/tailwindcss/dist/lib.mjs:28:759)
    at async Je (file:///home/spaceemotion/code/nc-website/novelcrafter/node_modules/.pnpm/@tailwindcss+node@4.0.0-beta.3/node_modules/@tailwindcss/node/dist/index.mjs:10:2860)
```

We could add a `@import "tailwindcss"` directive into the style tag, but that would import tailwind twice, and overwrite any extras we have in the main css (like custom colors, fonts, ...).

I thought the updates to the vite plugin resolution might have fixed it, but that doesn't seem to be the case (I also noticed that the plugin still depends on Vite v5, whereas v6 just came out recently).

**Comment by spaceemotion** [comment]
I seem to recall this being an issue in TailwindCSS v3 as well, where I had to import the config in the vue components like so:

```vue
<style>
@config "../../../../tailwind.config.js";

/* actual stylesheet that uses the tailwind stuff */
</style>
```
