### ISSUE TITLE
v4: Vite build fails on Cloudflare

### ISSUE THREAD

**Issue by MickL** [tailwindlabs/tailwindcss#15399]
**What version of Tailwind CSS are you using?**

4.0.0-beta.7

**What build tool (or framework if it abstracts the build tool) are you using?**

tailwindcss: 4.0.0-beta.7
vite: 6.0.3

**What version of Node.js are you using?**

Node: 22.11.0
Bun: 1.1.38

**Reproduction URL**

https://github.com/MickL/tailwind-vite

**Describe your issue**

Build works fine on my system (macOS) but when deploying to Cloudflare Pages I get the following error:

```
23:07:03.104 | $ vite build
23:07:03.768 | vite v6.0.3 building for production...
23:07:03.829 | transforming...
23:07:03.834 | ✓ 1 modules transformed.
23:07:03.840 | x Build failed in 40ms
23:07:03.840 | error during build:
23:07:03.840 | [@tailwindcss/vite:generate:build] Object not disposable
23:07:03.841 | file: /opt/buildhome/repo/index.css
23:07:03.841 | at q (file:///opt/buildhome/repo/node_modules/@tailwindcss/vite/dist/index.mjs:1:66)
23:07:03.841 | at P (file:///opt/buildhome/repo/node_modules/@tailwindcss/vite/dist/index.mjs:1:270)
23:07:03.841 | at Object.transform (file:///opt/buildhome/repo/node_modules/@tailwindcss/vite/dist/index.mjs:1:3715)
23:07:03.841 | at Object.handler (file:///opt/buildhome/repo/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:50845:15)
23:07:03.841 | at file:///opt/buildhome/repo/node_modules/rollup/dist/es/shared/node-entry.js:20812:40
23:07:03.847 | error: script "build" exited with code 1
23:07:03.850 | Failed: Error while executing user command. Exited with error code: 1
23:07:03.858 | Failed: build command exited with code: 1
23:07:04.505 | Failed: error occurred while running build command
```

I tried both in a Nuxt project as well as in a fresh clean Vite project: https://github.com/MickL/tailwind-vite

**Comment by rgripper** [comment]
This is because a call to dispose with `using` keyword fails on Node v20. But it starts working on Node v22

**Comment by MickL** [comment]
Cloudflare is using Node 18 for its build process.

I can confirm that it is working with Node 22. As a workaround one can add an environment variable or a file `.nvmrc` to specify Node version for the build process as described [here](https://developers.cloudflare.com/pages/configuration/build-image/#overriding-default-versions)

**Comment by RobinMalfait** [comment]
Hey!

This should be fixed by #15404, and will be available in the next beta release. As a temporary workaround, if you can bump Node.js to at least 18.20.x it should work again.

**Comment by ichavesbr** [comment]
I'm using mac and had the same issue with my vite project. What worked for me was deleting package-lock.json from the repo. Just in case I also added on .gitignore. No need to mess with node version.

"git rm --cached package-lock.json"
git commit -m "remove package-lock.json from repo"
git push

**Comment by MickL** [comment]
You should always commit package-lock, it is important for consistent building and collaboration

**Comment by ichavesbr** [comment]
Just found another solution. Downgraded eslint and @eslint/js both to version 9.39.4. Aparently can't be higher than 10.

Installed dependencies required for cloudflare but missing on my project:
```
"@emnapi/core": "^1.9.2",
"@emnapi/runtime": "^1.9.2",
"@emnapi/wasi-threads": "^1.2.1"
```

Here's my package.json:

```
"dependencies": {
    "@emnapi/core": "^1.9.2",
    "@emnapi/runtime": "^1.9.2",
    "@emnapi/wasi-threads": "^1.2.1",
    "@tailwindcss/vite": "^4.2.2",
    "react": "^19.2.4",
    "react-dom": "^19.2.4",
    "tailwindcss": "^4.2.2"
  },
  "devDependencies": {
    "@eslint/js": "9.39.4",
    "@types/node": "^25.5.2",
    "@types/react": "^19.2.14",
    "@types/react-dom": "^19.2.3",
    "@vitejs/plugin-react": "^6.0.1",
    "eslint": "9.39.4",
    "eslint-plugin-react-hooks": "^7.0.1",
    "eslint-plugin-react-refresh": "^0.5.2",
    "globals": "^17.4.0",
    "typescript": "~6.0.2",
    "typescript-eslint": "^8.58.0",
    "vite": "^8.0.5"
  }
```
