### ISSUE TITLE
ERROR during install tailwind config 

### ISSUE THREAD

**Issue by kyle-hensoon** [tailwindlabs/tailwindcss#2179]
hello , i try to install tailwind config with this command  " npx tailwind init tailwind.js --full
 " but it show a error

internal/modules/cjs/loader.js:628
  throw e;
  ^

Error: No valid exports main found for 'C:\Users\mosta\Desktop\gitjob\node_modules\colorette'
    at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
    at applyExports (internal/modules/cjs/loader.js:502:14)
    at resolveExports (internal/modules/cjs/loader.js:551:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\mosta\Desktop\gitjob\node_modules\autoprefixer\lib\autoprefixer.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:1144:30) {
  code: 'MODULE_NOT_FOUND'
}

**Comment by simonswiss** [comment]
@kyle-hensoon did you get it to work with the `tailwindcss` package? 

I'll close this issue for now, feel free to re-open if you're still having trouble.
