### ISSUE TITLE
Hugo + Tailwindcss + Netlify fails to build

### ISSUE THREAD

**Issue by jensamunch** [tailwindlabs/tailwindcss#2804]
### package.js
```
{
  "name": "website",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "./hugo server --gc --disableFastRender",
    "build": "hugo --minify --gc"
  },
  "keywords": [],
  "author": "",
  "license": "",
  "homepage": "https://github.com/findpace/website-v6",
  "dependencies": {
    "@fullhuman/postcss-purgecss": "3.0.0",
    "@tailwindcss/typography": "0.3.1",
    "@tailwindcss/ui": "0.7.2",
    "aos": "3.0.0-beta.6",
    "autoprefixer": "10.0.2",
    "postcss": "8.1.7",
    "postcss-cli": "8.3.0",
    "postcss-import": "13.0.0",
    "prettier": "^2.1.2",
    "prettier-plugin-go-template": "0.0.10",
    "tailwindcss": "^2.0.1"
  }
}
```

### postcss.config.js
```
// postcss.config.js
const autoprefixer = require("autoprefixer")({});

module.exports = {
  plugins: [
    require("postcss-import"),
    require("tailwindcss")("assets/css/tailwind.config.js"),
    ...(process.env.HUGO_ENVIRONMENT === "production" ? [autoprefixer] : []),
  ],
};
```

### output from Netlify
```
11:29:06 PM: ────────────────────────────────────────────────────────────────
11:29:06 PM:   1. build.command from netlify.toml                            
11:29:06 PM: ────────────────────────────────────────────────────────────────
11:29:06 PM: ​
11:29:06 PM: $ hugo --minify --gc
11:29:06 PM: Start building sites …
11:30:12 PM: Total in 65792 ms
11:30:12 PM: Error: Error building site: POSTCSS: failed to transform "css/styles.css" (text/css): TypeError: Object.entries(...).flatMap is not a function
11:30:12 PM:     at flattenColorPalette (/opt/build/repo/node_modules/tailwindcss/lib/util/flattenColorPalette.js:8:83)
11:30:12 PM:     at /opt/build/repo/node_modules/tailwindcss/lib/plugins/divideColor.js:27:53
11:30:12 PM:     at plugins.forEach.plugin (/opt/build/repo/node_modules/tailwindcss/lib/util/processPlugins.js:69:5)
11:30:12 PM:     at Array.forEach (<anonymous>)
11:30:12 PM:     at _default (/opt/build/repo/node_modules/tailwindcss/lib/util/processPlugins.js:63:11)
11:30:12 PM:     at /opt/build/repo/node_modules/tailwindcss/lib/processTailwindFeatures.js:60:54
11:30:12 PM:     at LazyResult.runOnRoot (/opt/build/repo/node_modules/postcss/lib/lazy-result.js:276:16)
11:30:12 PM:     at LazyResult.runAsync (/opt/build/repo/node_modules/postcss/lib/lazy-result.js:328:26)
11:30:12 PM: ​
11:30:12 PM: ────────────────────────────────────────────────────────────────
11:30:12 PM:   "build.command" failed                                        
11:30:12 PM: ────────────────────────────────────────────────────────────────
```

**Comment by adamwathan** [comment]
Tailwind CSS 2.0 requires Node 12 or higher, looks like your Netlify site is set up with an older version. Update your Node version using Netlify's environment variables 👍🏻

**Comment by jensamunch** [comment]
Man @adamwathan you kick ass! Really how cool what you're building with Tailwind is AND how incredibly devoted and helpful you are to the ecosystem! ❤️  🙌

**Comment by jensamunch** [comment]
![image](https://user-images.githubusercontent.com/1650140/99604753-1ecb3d00-29fe-11eb-9e40-9b59f49c995e.png)
 
All works

**Comment by adamwathan** [comment]
Awesome glad I could help!

**Comment by michael-observerly** [comment]
This still seems to fail for me when NODE_VERSION is set to 16 ...
