### ISSUE TITLE
Get issue with laravel mix config

### ISSUE THREAD

**Issue by deshiloh** [tailwindlabs/tailwindcss#2821]
Hi,

I'm trying to use tailwindcss 2 with laravel mix, i'm doing like this : 

```
mix.sass('assets/css/app.sass', 'dist/css')
    .options({
        processCssUrls: false,
        postCss: [
            require('tailwindcss')('./tailwind.config.js'),
            require('autoprefixer')
        ]
    })
```

I get : 
```
ERROR in ./assets/css/app.sass (./node_modules/css-loader??ref--8-2!./node_modules/postcss-loader/src??postcss0!./node_modules/sass-loader/dist/cjs.js??ref--8-4!./assets/css/app.sass)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: true is not a PostCSS plugin
    at Processor.normalize (/Users/deshiloh/Projects/Sites/tailwindtest/node_modules/postcss/lib/processor.js:168:15)
    at new Processor (/Users/deshiloh/Projects/Sites/tailwindtest/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/Users/deshiloh/Projects/Sites/tailwindtest/node_modules/postcss/lib/postcss.js:55:10)
    at /Users/deshiloh/Projects/Sites/tailwindtest/node_modules/postcss-loader/src/index.js:140:12
 @ ./assets/css/app.sass 2:14-196
```

Can you help me please ? Maybe i'm doing something wrong way.

**Comment by khalwat** [comment]
You need to be using the `-compat` version. Instructions are here:

https://tailwindcss.com/docs/installation#post-css-7-compatibility-build

**Comment by deshiloh** [comment]
Simple and clean ! Thank you so much for the help
