### ISSUE TITLE
Error when running npm run dev on Laravel 8.0

### ISSUE THREAD

**Issue by psmedia90** [tailwindlabs/tailwindcss#2825]
### Describe the problem:
When I run it with tailwind 1.3 everything runs just fine tried to upgrade to 2.0.1 and I get this error below
When I run NPM run Dev I get the following error:

Here is my package.json 
`
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --disable-host-check --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "@tailwindcss/ui": "^0.5.0",
        "axios": "^0.19",
        "cross-env": "^7.0",
        "laravel-mix": "^5.0.1",
        "lodash": "^4.17.19",
        "resolve-url-loader": "^3.1.0",
        "sass": "^1.29.0",
        "sass-loader": "^8.0.2",
        "vue-template-compiler": "^2.6.12"
    },
    "dependencies": {
        "tailwindcss": "^2.0.1"
    }
}

`
______________________________________________
[psmedia90@psm-powerhouse DjStu_L8]$ nrd

> @ dev /var/www/DjStu_L8
> npm run development

> @ development /var/www/DjStu_L8
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js

 	Additional dependencies must be installed. This will only take a moment.

 	Running: npm install sass-loader@8.* sass --save-dev --production=false

npm WARN @tailwindcss/custom-forms@0.2.1 requires a peer of tailwindcss@^1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @tailwindcss/typography@0.2.0 requires a peer of tailwindcss@^1.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN @tailwindcss/ui@0.5.0 requires a peer of tailwindcss@^1.5.1 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-nested@5.0.1 requires a peer of postcss@^8.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN tailwindcss@2.0.1 requires a peer of autoprefixer@^10.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN tailwindcss@2.0.1 requires a peer of postcss@^8.0.9 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.2 requires a peer of node-sass@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.2 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

 	Okay, done. The following packages have been installed and saved to your package.json dependencies list:

 	- sass-loader@8.*

 	- sass

 	Finished. Please run Mix again.

[psmedia90@psm-powerhouse DjStu_L8]$ nrd

> @ dev /var/www/DjStu_L8
> npm run development

> @ development /var/www/DjStu_L8
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js

98% after emitting SizeLimitsPlugin

 ERROR  Failed to compile with 2 errors                                                                                                         3:19:22 PM

 error  in ./resources/sass/app.scss

Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: getProcessedPlugins is not a function
    at /var/www/DjStu_L8/node_modules/tailwindcss/lib/processTailwindFeatures.js:71:83
    at LazyResult.run (/var/www/DjStu_L8/node_modules/postcss/lib/lazy-result.js:288:14)
    at LazyResult.asyncTick (/var/www/DjStu_L8/node_modules/postcss/lib/lazy-result.js:212:26)
    at LazyResult.asyncTick (/var/www/DjStu_L8/node_modules/postcss/lib/lazy-result.js:225:14)
    at /var/www/DjStu_L8/node_modules/postcss/lib/lazy-result.js:254:14
    at new Promise (<anonymous>)
    at LazyResult.async (/var/www/DjStu_L8/node_modules/postcss/lib/lazy-result.js:250:23)
    at LazyResult.then (/var/www/DjStu_L8/node_modules/postcss/lib/lazy-result.js:131:17)
    at /var/www/DjStu_L8/node_modules/postcss-loader/src/index.js:142:8
    at /var/www/DjStu_L8/node_modules/webpack/lib/NormalModule.js:316:20
    at /var/www/DjStu_L8/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /var/www/DjStu_L8/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/var/www/DjStu_L8/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /var/www/DjStu_L8/node_modules/postcss-loader/src/index.js:208:9

 error  in ./resources/sass/app.scss

Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: PostCSS plugin postcss-nested requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/var/www/DjStu_L8/node_modules/postcss/lib/processor.js:167:15)
    at new Processor (/var/www/DjStu_L8/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/var/www/DjStu_L8/node_modules/postcss/lib/postcss.js:55:10)
    at /var/www/DjStu_L8/node_modules/tailwindcss/lib/util/parseObjectStyles.js:24:33
    at arrayMap (/var/www/DjStu_L8/node_modules/lodash/lodash.js:639:23)
    at map (/var/www/DjStu_L8/node_modules/lodash/lodash.js:9580:14)
    at Function.flatMap (/var/www/DjStu_L8/node_modules/lodash/lodash.js:9283:26)
    at parseObjectStyles (/var/www/DjStu_L8/node_modules/tailwindcss/lib/util/parseObjectStyles.js:23:26)
    at parseObjectStyles (/var/www/DjStu_L8/node_modules/tailwindcss/lib/util/parseObjectStyles.js:20:12)
    at /var/www/DjStu_L8/node_modules/tailwindcss/lib/util/processPlugins.js:37:123
    at arrayMap (/var/www/DjStu_L8/node_modules/lodash/lodash.js:639:23)
    at map (/var/www/DjStu_L8/node_modules/lodash/lodash.js:9580:14)
    at Function.flatMap (/var/www/DjStu_L8/node_modules/lodash/lodash.js:9283:26)
    at parseStyles (/var/www/DjStu_L8/node_modules/tailwindcss/lib/util/processPlugins.js:37:26)
    at addComponents (/var/www/DjStu_L8/node_modules/tailwindcss/lib/util/processPlugins.js:131:18)
    at /var/www/DjStu_L8/node_modules/tailwindcss/lib/plugins/container.js:101:5
    at /var/www/DjStu_L8/node_modules/tailwindcss/lib/util/processPlugins.js:69:5
    at Array.forEach (<anonymous>)
    at _default (/var/www/DjStu_L8/node_modules/tailwindcss/lib/util/processPlugins.js:63:11)
    at /var/www/DjStu_L8/node_modules/tailwindcss/lib/processTailwindFeatures.js:60:54
    at LazyResult.run (/var/www/DjStu_L8/node_modules/postcss/lib/lazy-result.js:288:14)
    at LazyResult.asyncTick (/var/www/DjStu_L8/node_modules/postcss/lib/lazy-result.js:212:26)
    at LazyResult.asyncTick (/var/www/DjStu_L8/node_modules/postcss/lib/lazy-result.js:225:14)
    at /var/www/DjStu_L8/node_modules/postcss/lib/lazy-result.js:254:14
    at new Promise (<anonymous>)
    at LazyResult.async (/var/www/DjStu_L8/node_modules/postcss/lib/lazy-result.js:250:23)
    at LazyResult.then (/var/www/DjStu_L8/node_modules/postcss/lib/lazy-result.js:131:17)
    at /var/www/DjStu_L8/node_modules/postcss-loader/src/index.js:142:8

 @ ./resources/sass/app.scss 2:14-196

     Asset     Size   Chunks             Chunk Names
/js/app.js  596 KiB  /js/app  [emitted]  /js/app

ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: getProcessedPlugins is not a function
    at /var/www/DjStu_L8/node_modules/tailwindcss/lib/processTailwindFeatures.js:71:83
    at LazyResult.run (/var/www/DjStu_L8/node_modules/postcss/lib/lazy-result.js:288:14)
    at LazyResult.asyncTick (/var/www/DjStu_L8/node_modules/postcss/lib/lazy-result.js:212:26)
    at LazyResult.asyncTick (/var/www/DjStu_L8/node_modules/postcss/lib/lazy-result.js:225:14)
    at /var/www/DjStu_L8/node_modules/postcss/lib/lazy-result.js:254:14
    at new Promise (<anonymous>)
    at LazyResult.async (/var/www/DjStu_L8/node_modules/postcss/lib/lazy-result.js:250:23)
    at LazyResult.then (/var/www/DjStu_L8/node_modules/postcss/lib/lazy-result.js:131:17)
    at /var/www/DjStu_L8/node_modules/postcss-loader/src/index.js:142:8
    at /var/www/DjStu_L8/node_modules/webpack/lib/NormalModule.js:316:20
    at /var/www/DjStu_L8/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /var/www/DjStu_L8/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/var/www/DjStu_L8/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /var/www/DjStu_L8/node_modules/postcss-loader/src/index.js:208:9
 @ ./resources/sass/app.scss

ERROR in ./resources/sass/app.scss (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/sass-loader/dist/cjs.js??ref--5-4!./resources/sass/app.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: PostCSS plugin postcss-nested requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/var/www/DjStu_L8/node_modules/postcss/lib/processor.js:167:15)
    at new Processor (/var/www/DjStu_L8/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/var/www/DjStu_L8/node_modules/postcss/lib/postcss.js:55:10)
    at /var/www/DjStu_L8/node_modules/tailwindcss/lib/util/parseObjectStyles.js:24:33
    at arrayMap (/var/www/DjStu_L8/node_modules/lodash/lodash.js:639:23)
    at map (/var/www/DjStu_L8/node_modules/lodash/lodash.js:9580:14)
    at Function.flatMap (/var/www/DjStu_L8/node_modules/lodash/lodash.js:9283:26)
    at parseObjectStyles (/var/www/DjStu_L8/node_modules/tailwindcss/lib/util/parseObjectStyles.js:23:26)
    at parseObjectStyles (/var/www/DjStu_L8/node_modules/tailwindcss/lib/util/parseObjectStyles.js:20:12)
    at /var/www/DjStu_L8/node_modules/tailwindcss/lib/util/processPlugins.js:37:123
    at arrayMap (/var/www/DjStu_L8/node_modules/lodash/lodash.js:639:23)
    at map (/var/www/DjStu_L8/node_modules/lodash/lodash.js:9580:14)
    at Function.flatMap (/var/www/DjStu_L8/node_modules/lodash/lodash.js:9283:26)
    at parseStyles (/var/www/DjStu_L8/node_modules/tailwindcss/lib/util/processPlugins.js:37:26)
    at addComponents (/var/www/DjStu_L8/node_modules/tailwindcss/lib/util/processPlugins.js:131:18)
    at /var/www/DjStu_L8/node_modules/tailwindcss/lib/plugins/container.js:101:5
    at /var/www/DjStu_L8/node_modules/tailwindcss/lib/util/processPlugins.js:69:5
    at Array.forEach (<anonymous>)
    at _default (/var/www/DjStu_L8/node_modules/tailwindcss/lib/util/processPlugins.js:63:11)
    at /var/www/DjStu_L8/node_modules/tailwindcss/lib/processTailwindFeatures.js:60:54
    at LazyResult.run (/var/www/DjStu_L8/node_modules/postcss/lib/lazy-result.js:288:14)
    at LazyResult.asyncTick (/var/www/DjStu_L8/node_modules/postcss/lib/lazy-result.js:212:26)
    at LazyResult.asyncTick (/var/www/DjStu_L8/node_modules/postcss/lib/lazy-result.js:225:14)
    at /var/www/DjStu_L8/node_modules/postcss/lib/lazy-result.js:254:14
    at new Promise (<anonymous>)
    at LazyResult.async (/var/www/DjStu_L8/node_modules/postcss/lib/lazy-result.js:250:23)
    at LazyResult.then (/var/www/DjStu_L8/node_modules/postcss/lib/lazy-result.js:131:17)
    at /var/www/DjStu_L8/node_modules/postcss-loader/src/index.js:142:8
 @ ./resources/sass/app.scss 2:14-196
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/psmedia90/.npm/_logs/2020-11-19T20_19_22_771Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/psmedia90/.npm/_logs/2020-11-19T20_19_22_821Z-debug.log

### Link to a minimal reproduction:

Not sure how to reproduce this on another machine I am running fedora server 32

**Comment by kevintresuelo** [comment]
Same problem here, I suppose it roots from the different PostCSS versions.

**Comment by RikoDEV** [comment]
TailwindCSS 2.0 requires **laravel-mix** version 6.0.0 (currently beta). Working package.json:

```
    "devDependencies": {
        "axios": "^0.21",
        "cross-env": "^7.0",
        "laravel-mix": "^6.0.0-beta.14",
        "lodash": "^4.17.19",
        "postcss-import": "^13.0.0",
        "purify-css": "^1.2.5",
        "purifycss-webpack": "^0.7.0",
        "resolve-url-loader": "^3.1.2",
        "tailwindcss": "^2.0.0",
        "vue-template-compiler": "^2.6.12"
    },
```

**Comment by psmedia90** [comment]
## they're doing that update this is what I get for an error

_____________________________________________________

[psmedia90@psm-powerhouse DjStu_L8]$ nrd

> @ dev /var/www/DjStu_L8
> npm run development


> @ development /var/www/DjStu_L8
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js

[webpack-cli] /var/www/DjStu_L8/node_modules/laravel-mix/src/Log.js:5
    static testing = false;
                   ^

SyntaxError: Unexpected token =
    at new Script (vm.js:74:7)
    at NativeCompileCache._moduleCompile (/var/www/DjStu_L8/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/var/www/DjStu_L8/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/var/www/DjStu_L8/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/var/www/DjStu_L8/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:1:73)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/psmedia90/.npm/_logs/2020-11-20T17_45_42_807Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/psmedia90/.npm/_logs/2020-11-20T17_45_42_849Z-debug.log
[psmedia90@psm-powerhouse DjStu_L8]$

**Comment by hcphoon01** [comment]
I'm also getting this issue, I've tried upgrading laravel mix to 6.0.0-beta.14 but whenever I do it automatically downloads PostCSS v8 which then goes back to this error `Error: PostCSS plugin tailwindcss requires PostCSS 8.`

**Comment by psmedia90** [comment]
> I'm also getting this issue, I've tried upgrading laravel mix to 6.0.0-beta.14 but whenever I do it automatically downloads PostCSS v8 which then goes back to this error `Error: PostCSS plugin tailwindcss requires PostCSS 8.`

I know I even tried what @RikoDEV And it did not work got A different error As you can see in my last post

**Comment by Lunaversitay** [comment]
> 
> #### this is what is get when I update this is what I get for an error
> 
> [psmedia90@psm-powerhouse DjStu_L8]$ nrd
> 
> > @ dev /var/www/DjStu_L8
> > npm run development
> 
> > @ development /var/www/DjStu_L8
> > cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js
> 
> [webpack-cli] /var/www/DjStu_L8/node_modules/laravel-mix/src/Log.js:5
> static testing = false;
> ^
> 
> SyntaxError: Unexpected token =
> at new Script (vm.js:74:7)
> at NativeCompileCache._moduleCompile (/var/www/DjStu_L8/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
> at Module._compile (/var/www/DjStu_L8/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
> at Module.load (internal/modules/cjs/loader.js:599:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
> at Function.Module._load (internal/modules/cjs/loader.js:530:3)
> at Module.require (internal/modules/cjs/loader.js:637:17)
> at require (/var/www/DjStu_L8/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
> at Object. (/var/www/DjStu_L8/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:1:73)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js`
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the @ development script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /home/psmedia90/.npm/_logs/2020-11-20T17_45_42_807Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! @ dev: `npm run development`
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the @ dev script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /home/psmedia90/.npm/_logs/2020-11-20T17_45_42_849Z-debug.log
> [psmedia90@psm-powerhouse DjStu_L8]$

Solved this issue by updating nodejs to 14.x

**Comment by psmedia90** [comment]
@Lunaversitay  thank you worked like a charm

**Comment by vesper8** [comment]
I'm on Node 15 and still having this issue. The instructions for how to install Tailwind with Laravel just don't work
