### ISSUE TITLE
Error: Cannot find module 'core-js/fn/array'

### ISSUE THREAD

**Issue by redsuperbat** [tailwindlabs/tailwindcss#3089]
### Describe the problem:

Seems like there is a problem between postcss 7 compatibility build and core-js. I'm stuck at the error below and i don't know how to solve it.

### Steps to reproduce

This girhub repo has the issue specified: https://github.com/redsuperbat/website-portfolio/tree/next

Install the postcss 7 comparability version of tailwindcss in a vue 3 project.

run `npm run serve` 

This error occurs. However this error does not occur once, it occurs in every vue component that is using tailwindcss classes. So the terminal is filled with ~30 similar errors complaining about core-js/fn/array

```
 error  in ./node_modules/primevue/components/card/Card.vue?vue&type=style&index=0&lang=css

Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Cannot find module 'core-js/fn/array'
Require stack:
- /home/max/Projects/website-portfolio/tailwind.config.js
- /home/max/Projects/website-portfolio/node_modules/tailwindcss/lib/index.js
- /home/max/Projects/website-portfolio/node_modules/import-from/index.js
- /home/max/Projects/website-portfolio/node_modules/import-cwd/index.js
- /home/max/Projects/website-portfolio/node_modules/postcss-load-config/src/options.js
- /home/max/Projects/website-portfolio/node_modules/postcss-load-config/src/index.js
- /home/max/Projects/website-portfolio/node_modules/postcss-loader/src/index.js
- /home/max/Projects/website-portfolio/node_modules/loader-runner/lib/loadLoader.js
- /home/max/Projects/website-portfolio/node_modules/loader-runner/lib/LoaderRunner.js
- /home/max/Projects/website-portfolio/node_modules/webpack/lib/NormalModule.js
- /home/max/Projects/website-portfolio/node_modules/webpack/lib/NormalModuleFactory.js
- /home/max/Projects/website-portfolio/node_modules/webpack/lib/Compiler.js
- /home/max/Projects/website-portfolio/node_modules/webpack/lib/webpack.js
- /home/max/Projects/website-portfolio/node_modules/@vue/cli-service/lib/commands/serve.js
- /home/max/Projects/website-portfolio/node_modules/@vue/cli-service/lib/Service.js
- /home/max/Projects/website-portfolio/node_modules/@vue/cli-service/bin/vue-cli-service.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)
    at Function.Module._load (node:internal/modules/cjs/loader:763:27)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/max/Projects/website-portfolio/tailwind.config.js:1:21)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at /home/max/Projects/website-portfolio/node_modules/tailwindcss/lib/index.js:76:107
    at /home/max/Projects/website-portfolio/node_modules/tailwindcss/lib/processTailwindFeatures.js:52:20
    at LazyResult.run (/home/max/Projects/website-portfolio/node_modules/postcss/lib/lazy-result.js:288:14)
    at LazyResult.asyncTick (/home/max/Projects/website-portfolio/node_modules/postcss/lib/lazy-result.js:212:26)
    at LazyResult.asyncTick (/home/max/Projects/website-portfolio/node_modules/postcss/lib/lazy-result.js:225:14)

 @ ./node_modules/vue-style-loader??ref--6-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-1-1!./node_modules/vue-loader-v16/dist/stylePostLoader.js!./node_modules/postcss-loader/src??ref--6-oneOf-1-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./node_modules/primevue/components/card/Card.vue?vue&type=style&index=0&lang=css 4:14-314 14:3-18:5 15:22-322
 @ ./node_modules/primevue/components/card/Card.vue?vue&type=style&index=0&lang=css
 @ ./node_modules/primevue/components/card/Card.vue
 @ ./node_modules/primevue/card.js
 @ ./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/ProjectCard.vue?vue&type=script&lang=ts
 @ ./src/components/ProjectCard.vue?vue&type=script&lang=ts
 @ ./src/components/ProjectCard.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/Projects.vue?vue&type=script&lang=ts
 @ ./src/components/Projects.vue?vue&type=script&lang=ts
 @ ./src/components/Projects.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/views/Home.vue?vue&type=script&lang=ts
 @ ./src/views/Home.vue?vue&type=script&lang=ts
 @ ./src/views/Home.vue
 @ ./src/router/index.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://192.168.1.85:8081&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts
```

**Comment by adamwathan** [comment]
Hey! Please provide a repository that reproduces so we don't have to recreate your setup from scratch.

**Comment by redsuperbat** [comment]
Link in the issue to the affected repo

**Comment by redsuperbat** [comment]
I cloned the repo to another computer, there it works fine. Seems like this is an issue related to local files

**Comment by adamwathan** [comment]
Ah weird! Well glad to know it's not a Tailwind issue at least and that you were able to sort it out 👍🏻

**Comment by yulecc** [comment]
good
