### ISSUE TITLE
Cannot use defaultTheme (const theme = require('tailwindcss/defaultTheme');) inside extended (presets) config files.

### ISSUE THREAD

**Issue by terryupton** [tailwindlabs/tailwindcss#3542]
### Describe the problem:
I am running into a problem when building with Laravel mix and using a `const theme` inside an extended config file.
Here is the example setup.

**tailwind.config.js**
```
module.exports = {
  presets: [
    // require('./src/tailwind/tailwind.brand.js'),
    // require('./src/tailwind/tailwind.project.js'),
    require('./src/tailwind/tailwind.colors.js'),
    require('./src/tailwind/tailwind.spacing.js'), //this is the problem file
    require('./src/tailwind/tailwind.opacity.js'),
    require('./src/tailwind/tailwind.zindex.js'),
    require('./src/tailwind/tailwind.grid.js')
  ],
  purge: {
    mode: 'all',
    content: [
      './templates/**/*.html',
      './templates/**/*.php',
      './src/**/*.js'
    ],
    
    options: {
      whitelistPatterns: [/lazyload/, /grayscale-up/, /blur-up/],
    }
  },
  theme: {
    container: {
      center: true,
      padding: '1.5rem',
    },
  },
  variants: {
    extend: {
      // display: ['group-hover']
      // translate: ['group-hover']
    }
  },
  corePlugins: {},
  plugins: []
};
```

**tailwind.spacing.js**
```
const theme = require('tailwindcss/defaultTheme');

module.exports = {
  theme: {
    extend: {
      margin: {
        'flood': 'calc(50% - 50vw)'
      },
      
      minWidth: {
        ...theme('spacing'),
      },
      
      maxWidth: {
        ...theme('spacing'),
        '7xl': '80rem',
        '8xl': '90rem',
        '9xl': '100rem',
      },
    }
  }
};
```
###Error
Here is the error I am getting:
```
Module build failed (from ../../../../node_modules_local/boilerplate-base/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../../../../node_modules_local/boilerplate-base/node_modules/postcss-loader/dist/cjs.js):
TypeError: theme is not a function
    at Object.<anonymous> (/Users/terryupton/Dropbox/Amasci/Websites/boilerplate-base/tailwind.spacing.js:11:12)
    at Module._compile (/Users/terryupton/node_modules_local/boilerplate-base/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (/Users/terryupton/node_modules_local/boilerplate-base/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/terryupton/Dropbox/Amasci/Websites/boilerplate-base/tailwind.config.js:6:5)
    at Module._compile (/Users/terryupton/node_modules_local/boilerplate-base/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at processResult (/Users/terryupton/node_modules_local/boilerplate-base/node_modules/webpack/lib/NormalModule.js:598:19)
    at /Users/terryupton/node_modules_local/boilerplate-base/node_modules/webpack/lib/NormalModule.js:692:5
    at /Users/terryupton/node_modules_local/boilerplate-base/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/terryupton/node_modules_local/boilerplate-base/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/Users/terryupton/node_modules_local/boilerplate-base/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/Users/terryupton/node_modules_local/boilerplate-base/node_modules/postcss-loader/dist/index.js:104:7)

1 ERROR in child compilations
```

###Testing
If I remove this file from the presets then the build compiles and completes successfully.
If I move this file to the top/same level as `tailwind.config.js` then I still get this error as I thought it might have been path related.

### Link to a minimal reproduction:
Here is the repo:
https://github.com/terryupton/boilerplate-base/tree/development

**Comment by adamwathan** [comment]
Hey! You need to declare those sections as a function so they can receive the `theme` helper, in your code it's not defined as the error says.

```js
const theme = require('tailwindcss/defaultTheme');

module.exports = {
  theme: {
    extend: {
      margin: {
        'flood': 'calc(50% - 50vw)'
      },
      
      minWidth: (theme) => ({
        ...theme('spacing'),
      }),
      
      maxWidth: (theme) => ({
        ...theme('spacing'),
        '7xl': '80rem',
        '8xl': '90rem',
        '9xl': '100rem',
      }),
    }
  }
};
```

**Comment by terryupton** [comment]
Sorry @adamwathan i don't follow?
Could you help with an example?
Thanks.

**Comment by terryupton** [comment]
Thanks @adamwathan - what a silly mistake ☺️🙃
