### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by jacksoncool** [tailwindlabs/tailwindcss#3764]
Every time I try to build a tailwind output file, I get the following error:

tailwindcss 2.0.3

   � Building: src/tailwind.css
  
   � CssSyntaxError: C:\tw-v2\src\tailwind.css:1:1: Unknown word
    at Input.error (C:\AppData\Roaming\npm-cache\_npx\27512\node_modules\tailwindcss-cli\node_modules\postcss\lib\input.js:121:16)
    at Parser.unknownWord (C:\AppData\Roaming\npm-cache\_npx\27512\node_modules\tailwindcss-cli\node_modules\postcss\lib\parser.js:518:22)
    at Parser.other (C:\AppData\Roaming\npm-cache\_npx\27512\node_modules\tailwindcss-cli\node_modules\postcss\lib\parser.js:149:12)
    at Parser.parse (C:\AppData\Roaming\npm-cache\_npx\27512\node_modules\tailwindcss-cli\node_modules\postcss\lib\parser.js:59:16)
    at parse (C:\AppData\Roaming\npm-cache\_npx\27512\node_modules\tailwindcss-cli\node_modules\postcss\lib\parse.js:11:12)    
    at new LazyResult (C:\AppData\Roaming\npm-cache\_npx\27512\node_modules\tailwindcss-cli\node_modules\postcss\lib\lazy-result.js:122:16)
    at Processor.process (C:\AppData\Roaming\npm-cache\_npx\27512\node_modules\tailwindcss-cli\node_modules\postcss\lib\processor.js:33:12)
    at C:\AppData\Roaming\npm-cache\_npx\27512\node_modules\tailwindcss-cli\node_modules\tailwindcss\lib\cli\compile.js:48:43  
    at new Promise (<anonymous>)
    at compile (C:\AppData\Roaming\npm-cache\_npx\27512\node_modules\tailwindcss-cli\node_modules\tailwindcss\lib\cli\compile.js:47:10)

Any help is appreciated.

**Comment by bradlc** [comment]
Closing this as it's dated and no reproduction was provided. Please open a new issue with a minimal reproduction if you're still having problems 👍
