### ISSUE TITLE
Cannot find stdin on track modified using Snowpack

### ISSUE THREAD

**Issue by cschmatzler** [tailwindlabs/tailwindcss#3944]
Trying out the new compiler with snowpack. Very minimal setup, with `@snowpack/plugin-postcss` added to the snowpack config and my postcss config looking like

```
module.exports = {
  plugins: {
    '@tailwindcss/jit': {},
    autoprefixer: {},
  }
};
```
Jusing the normal `tailwindcss` PostCSS plugin works just fine, but with JIT I am getting the following error on running `yarn snowpack build`:

```
[snowpack] ! building dependencies...
(node:1378370) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: postcss
Error: ENOENT: no such file or directory, stat '/home/cschmatzler/development/papertrail/lynx/assets/stdin'
    at Object.statSync (fs.js:1086:3)
    at trackModified (/home/cschmatzler/development/papertrail/lynx/assets/node_modules/@tailwindcss/jit/src/lib/setupContext.js:188:26)
    at /home/cschmatzler/development/papertrail/lynx/assets/node_modules/@tailwindcss/jit/src/lib/setupContext.js:653:38
    at /home/cschmatzler/development/papertrail/lynx/assets/node_modules/@tailwindcss/jit/src/index.js:34:49
    at LazyResult.runOnRoot (/home/cschmatzler/development/papertrail/lynx/assets/node_modules/postcss/lib/lazy-result.js:303:16)
    at LazyResult.runAsync (/home/cschmatzler/development/papertrail/lynx/assets/node_modules/postcss/lib/lazy-result.js:355:26)
    at LazyResult.async (/home/cschmatzler/development/papertrail/lynx/assets/node_modules/postcss/lib/lazy-result.js:205:30)
    at LazyResult.then (/home/cschmatzler/development/papertrail/lynx/assets/node_modules/postcss/lib/lazy-result.js:190:17)
    at /home/cschmatzler/development/papertrail/lynx/assets/node_modules/postcss-cli/index.js:233:10
    at async Promise.all (index 0) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/home/cschmatzler/development/papertrail/lynx/assets/stdin'
}
    at makeError (/home/cschmatzler/development/papertrail/lynx/assets/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/cschmatzler/development/papertrail/lynx/assets/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.transform (/home/cschmatzler/development/papertrail/lynx/assets/node_modules/@snowpack/plugin-postcss/plugin.js:13:24)
    at async runPipelineTransformStep (/home/cschmatzler/development/papertrail/lynx/assets/node_modules/snowpack/lib/index.js:75331:32)
    at async Object.buildFile (/home/cschmatzler/development/papertrail/lynx/assets/node_modules/snowpack/lib/index.js:75416:29)
    at async FileBuilder.buildFile (/home/cschmatzler/development/papertrail/lynx/assets/node_modules/snowpack/lib/index.js:111929:15)
    at async run (/home/cschmatzler/development/papertrail/lynx/assets/node_modules/snowpack/lib/index.js:50375:29)
```

**Comment by bradlc** [comment]
Hey all. `@snowpack/plugin-postcss` was updated last week and here's how we recommend using Tailwind JIT with Snowpack:

1. Ensure that you are using the latest `tailwindcss` canary release (>= `2.2.0-canary.9`): `npm install -D tailwindcss@canary`
2. Ensure that you are using the latest version of `@snowpack/plugin-postcss` (>= `1.4.0`)
3. Set the `TAILWIND_DISABLE_TOUCH` environment variable to `true`. This enables an alternative watch method which is now compatible with `@snowpack/plugin-postcss`
4. Ensure that you are **_not_** using the `devOptions.tailwindConfig` Snowpack option

Here is a bare-bones example project: https://github.com/bradlc/jit-snowpack

If you are still having problems after following these instructions please open a new issue with a reproduction, thanks!
