### ISSUE TITLE
The `transform` class does not exist. If `transform` is a custom class, make sure it is defined within a `@layer` directive.

### ISSUE THREAD

**Issue by g0shed** [tailwindlabs/tailwindcss#4682]
### What version of Tailwind CSS are you using?

2.2.0

### What build tool (or framework if it abstracts the build tool) are you using?

vite

### What version of Node.js are you using?

16.2.0

### What browser are you using?

Chorme

### What operating system are you using?

Windows WSL Ubuntu

### Reproduction repository

https://github.com/

### Describe your issue

trying to build tailwind 2.2 on vite and this is happening

`CssSyntaxError: [...]/src/components/core/styles/Toolbar.scss:56:3: The `transform` class does not exist. If `transform` is a custom class, make sure it is defined within a `@layer` directive.
    at Input.error ([...]/node_modules/vite/node_modules/postcss/lib/input.js:123:16)
    at AtRule.error ([...]/node_modules/vite/node_modules/postcss/lib/node.js:60:32)
    at processApply ([...]/node_modules/tailwindcss/lib/jit/lib/expandApplyAtRules.js:172:23)    at [...]/node_modules/tailwindcss/lib/jit/lib/expandApplyAtRules.js:229:5
    at [...]/node_modules/tailwindcss/lib/jit/processTailwindFeatures.js:54:46
    at [...]/node_modules/tailwindcss/lib/jit/index.js:25:56
    at LazyResult.runOnRoot ([...]/node_modules/vite/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync ([...]/node_modules/vite/node_modules/postcss/lib/lazy-result.js:391:26)
    at async compileCSS ([...]/node_modules/vite/dist/node/chunks/dep-bc228bbb.js:23455:27)
    at async Object.transform ([...]/node_modules/vite/dist/node/chunks/dep-bc228bbb.js:23076:50)`

if I downgrade to 2.1.4 everything works

**Comment by sachinraja** [comment]
Not sure if this is the problem, but the dependency tracking system for Vite is not compatible yet. They say this in the [release notes](https://github.com/tailwindlabs/tailwindcss/releases/tag/v2.2.0). They also list potential solutions there.

**Comment by adamwathan** [comment]
Hey! As mentioned in the release notes, the transform class is no longer necessary when using JIT mode and has been removed:

https://github.com/tailwindlabs/tailwindcss/releases/tag/v2.2.0#transforms-and-filters-don-t-need-to-be-enabled-in-just-in-time-mode

So the error is correct, you can just delete transform from the list of applied classes and everything will be good 👍🏻
