### ISSUE TITLE
Latest Tailwind and @tailwindcss/jit compilation - TypeError: Cannot read property 'theme' of undefined

### ISSUE THREAD

**Issue by ConnorJamesLow** [tailwindlabs/tailwindcss#5109]
### What version of Tailwind CSS are you using?

v2.2.7 (jit v 0.1.18)

### What build tool (or framework if it abstracts the build tool) are you using?

postcss-cli 8.3.1

### What version of Node.js are you using?

v14.12.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/ConnorJamesLow/tailwind-theme-issue-reproduction

### Describe your issue

When updating to the latest version of tailwindcss, @tailwindcss/jit stopped working. Here's the full output (as noted, using postcss-cli):

```log
> mre@1.0.0 dev C:\Users\conno\source\opensource\tailwind\mre
> npx postcss src/index.css -o ./dist/site.jit.css --env development -w --verbose

Processing src\index.css...

TypeError: Cannot read property 'theme' of undefined
    at _default (C:\Users\conno\source\opensource\tailwind\mre\node_modules\tailwindcss\lib\lib\substituteScreenAtRules.js:16:5)
    at C:\Users\conno\source\opensource\tailwind\mre\node_modules\@tailwindcss\jit\src\index.js:50:11
    at LazyResult.runOnRoot (C:\Users\conno\source\opensource\tailwind\mre\node_modules\postcss\lib\lazy-result.js:339:16)
    at LazyResult.runAsync (C:\Users\conno\source\opensource\tailwind\mre\node_modules\postcss\lib\lazy-result.js:391:26)
    at LazyResult.async (C:\Users\conno\source\opensource\tailwind\mre\node_modules\postcss\lib\lazy-result.js:221:30)
    at LazyResult.then (C:\Users\conno\source\opensource\tailwind\mre\node_modules\postcss\lib\lazy-result.js:206:17)
    at C:\Users\conno\source\opensource\tailwind\mre\node_modules\postcss-cli\index.js:233:10
    at async Promise.all (index 0)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mre@1.0.0 dev: `npx postcss src/index.css -o ./dist/site.jit.css --env development -w --verbose`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mre@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\conno\AppData\Roaming\npm-cache\_logs\2021-07-29T02_01_33_612Z-debug.log
```

**Comment by ConnorJamesLow** [comment]
Nevermind. I was using the old `@tailwindcss/jit` instead of just setting `mode: 'jit'` in tailwind.config.js. This seems to fix it.

If anyone needs to use `@tailwindcss/jit` for any reason, you can also fix it by updating this bit of *@tailwindcss\jit\src\index.js*:

```js
// around line 45
return postcss([
  removeLayerAtRules(context),
  expandTailwindAtRules(context, registerDependency),
  expandApplyAtRules(context),

  // begin changes
  evaluateTailwindFunctions(context), // instead of evaluateTailwindFunctions(context.tailwindConfig),
  substituteScreenAtRules(context), // instead of substituteScreenAtRules(context.tailwindConfig),
  // end changes.

  collapseAdjacentRules(context),
]).process(root, { from: undefined })
```

**Comment by simonswiss** [comment]
Nice one, moving this to discussions, because it came up a few times.
