### ISSUE TITLE
Usage of active pseudo class in @apply file causes build process to crash

### ISSUE THREAD

**Issue by oneserv-heuser** [tailwindlabs/tailwindcss#5185]
### What version of Tailwind CSS are you using?

2.2.7

### What build tool (or framework if it abstracts the build tool) are you using?

Just tailwind

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

Doesnt matter, build process is failing

### What operating system are you using?

Linux

### Reproduction repository

https://github.com/oneserv-heuser/tailwindcss-mnwe

### Describe your issue

The usage of `@apply` with the active pseudo class causes the tailwind build process to crash with the following error:
<details>
<summary>Error details</summary>

```
(node:15282) UnhandledPromiseRejectionWarning: CssSyntaxError: /mnt/c/Users/heuser/PhpstormProjects/tailwindcss-mnwe/tailwind.css:6:16: The `active:underline` class does not exist, but `hover:underline` does. If you're sure that `active:underline` exists, make sure that any `@import` statements are being properly processed before Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.
    at /mnt/c/Users/heuser/PhpstormProjects/tailwindcss-mnwe/tailwind.css:6:9
    at Input.error (/mnt/c/Users/heuser/PhpstormProjects/tailwindcss-mnwe/node_modules/tailwindcss/peers/index.js:57624:16)
    at AtRule.error (/mnt/c/Users/heuser/PhpstormProjects/tailwindcss-mnwe/node_modules/tailwindcss/peers/index.js:58713:32)
    at /mnt/c/Users/heuser/PhpstormProjects/tailwindcss-mnwe/node_modules/tailwindcss/lib/lib/substituteClassApplyAtRules.js:240:20
    at Array.forEach (<anonymous>)
    at extractUtilityRules (/mnt/c/Users/heuser/PhpstormProjects/tailwindcss-mnwe/node_modules/tailwindcss/lib/lib/substituteClassApplyAtRules.js:226:18)
    at /mnt/c/Users/heuser/PhpstormProjects/tailwindcss-mnwe/node_modules/tailwindcss/lib/lib/substituteClassApplyAtRules.js:290:22
    at /mnt/c/Users/heuser/PhpstormProjects/tailwindcss-mnwe/node_modules/tailwindcss/peers/index.js:56958:16
    at /mnt/c/Users/heuser/PhpstormProjects/tailwindcss-mnwe/node_modules/tailwindcss/peers/index.js:56881:18
    at Rule.each (/mnt/c/Users/heuser/PhpstormProjects/tailwindcss-mnwe/node_modules/tailwindcss/peers/index.js:56867:16)
    at Rule.walk (/mnt/c/Users/heuser/PhpstormProjects/tailwindcss-mnwe/node_modules/tailwindcss/peers/index.js:56878:17)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15282) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15282) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

</details>

Replacing active with hover fixes the issue. I also found no other pseudo classes that causes this crash.
The problem only occurs in the build process, with JIT everything works.
Adding the active variant to the tailwind config doesn't fix the problem.

**Comment by adamwathan** [comment]
Hey! The `active` pseudo-class is not enabled for any utilities by default. You'll need to create a `tailwind.config.js` file and enable the `active` variant for the `textDecoration` plugin:

```js
module.exports = {
  theme: {},
  variants: {
    extend: {
      textDecoration: ['active'],
    },
  },
  plugins: [],
}
```

Relevant docs: https://tailwindcss.com/docs/hover-focus-and-other-states#active

**Comment by oneserv-heuser** [comment]
@adamwathan  Yeah well, found our mistake now. We've added "text" instead of "textDecoration" to the tailwind.config.js. Thanks for helping out!
