### ISSUE TITLE
npm install -D tailwindcss@npm:@tailwindcss/postcss7-compat failed

### ISSUE THREAD

**Issue by smoothdvd** [tailwindlabs/tailwindcss#5578]
**What version of Tailwind CSS are you using?**
tailwindcss@npm:@tailwindcss/postcss7-compat

**What version of Node.js are you using?**
v16.9.1

**What operating system are you using?**

macOS 11.6

**Describe your issue**

npm 7.24.0

run "npm install -D tailwindcss@npm:@tailwindcss/postcss7-compat"

nom report:

npm ERR! Invalid Version: 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alexgao/.npm/_logs/2021-09-23T06_52_57_652Z-debug.log

run 0 verbose cli [
0 verbose cli   '/opt/homebrew/Cellar/node/16.9.1/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   '-D',
0 verbose cli   'tailwindcss@npm:@tailwindcss/postcss7-compat'
0 verbose cli ]
1 info using npm@7.24.0
2 info using node@v16.9.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/alexgao/Dev/chengshi-news-miniapp/.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:/Users/alexgao/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 5ms
19 timing npm:load:configload Completed in 5ms
20 timing npm:load:setTitle Completed in 2ms
21 timing npm:load:setupLog Completed in 1ms
22 timing config:load:flatten Completed in 1ms
23 timing npm:load:cleanupLog Completed in 1ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 0ms
26 timing npm:load Completed in 10ms
27 timing arborist:ctor Completed in 1ms
28 timing idealTree:init Completed in 199ms
29 timing idealTree:userRequests Completed in 2ms
30 silly idealTree buildDeps
31 silly fetch manifest tailwindcss@npm:@tailwindcss/postcss7-compat
32 timing arborist:ctor Completed in 0ms
33 http fetch GET 200 https://registry.npmjs.org/@tailwindcss%2fpostcss7-compat 155ms (cache hit)
34 silly placeDep ROOT tailwindcss@2.2.14 OK for: chengshi-news-miniapp@0.1.0 want: npm:@tailwindcss/postcss7-compat
35 silly fetch manifest arg@^5.0.1
36 silly fetch manifest chalk@^4.1.2
37 silly fetch manifest color@^4.0.1
38 silly fetch manifest cosmiconfig@^7.0.1
39 silly fetch manifest detective@^5.2.0
40 silly fetch manifest didyoumean@^1.2.2
41 silly fetch manifest dlv@^1.1.3
42 silly fetch manifest fs-extra@^10.0.0
43 silly fetch manifest glob-parent@^6.0.1
44 silly fetch manifest html-tags@^3.1.0
45 silly fetch manifest is-color-stop@^1.1.0
46 silly fetch manifest lodash.topath@^4.5.2
47 silly fetch manifest modern-normalize@^1.1.0
48 silly fetch manifest node-emoji@^1.11.0
49 silly fetch manifest object-hash@^2.2.0
50 silly fetch manifest postcss-functions@^3
51 silly fetch manifest postcss-js@^2
52 silly fetch manifest postcss-load-config@^3.1.0
53 silly fetch manifest postcss-nested@^4
54 silly fetch manifest postcss-value-parser@^4.1.0
55 silly fetch manifest pretty-hrtime@^1.0.3
56 silly fetch manifest purgecss@^4.0.3
57 silly fetch manifest quick-lru@^5.1.1
58 silly fetch manifest reduce-css-calc@^2.1.8
59 silly fetch manifest tmp@^0.2.1
60 http fetch GET 200 https://registry.npmjs.org/glob-parent 19ms (cache hit)
61 http fetch GET 200 https://registry.npmjs.org/color 19ms (cache hit)
62 http fetch GET 200 https://registry.npmjs.org/fs-extra 20ms (cache hit)
63 http fetch GET 200 https://registry.npmjs.org/postcss-js 19ms (cache hit)
64 http fetch GET 200 https://registry.npmjs.org/modern-normalize 19ms (cache hit)
65 http fetch GET 200 https://registry.npmjs.org/chalk 21ms (cache hit)
66 http fetch GET 200 https://registry.npmjs.org/didyoumean 21ms (cache hit)
67 http fetch GET 200 https://registry.npmjs.org/is-color-stop 20ms (cache hit)
68 http fetch GET 200 https://registry.npmjs.org/postcss-load-config 20ms (cache hit)
69 http fetch GET 200 https://registry.npmjs.org/postcss-value-parser 20ms (cache hit)
70 http fetch GET 200 https://registry.npmjs.org/lodash.topath 21ms (cache hit)
71 http fetch GET 200 https://registry.npmjs.org/node-emoji 21ms (cache hit)
72 http fetch GET 200 https://registry.npmjs.org/dlv 22ms (cache hit)
73 http fetch GET 200 https://registry.npmjs.org/pretty-hrtime 20ms (cache hit)
74 http fetch GET 200 https://registry.npmjs.org/purgecss 21ms (cache hit)
75 http fetch GET 200 https://registry.npmjs.org/object-hash 22ms (cache hit)
76 http fetch GET 200 https://registry.npmjs.org/postcss-functions 23ms (cache hit)
77 http fetch GET 200 https://registry.npmjs.org/quick-lru 22ms (cache hit)
78 http fetch GET 200 https://registry.npmjs.org/postcss-nested 23ms (cache hit)
79 http fetch GET 200 https://registry.npmjs.org/html-tags 24ms (cache hit)
80 http fetch GET 200 https://registry.npmjs.org/reduce-css-calc 23ms (cache hit)
81 http fetch GET 200 https://registry.npmjs.org/cosmiconfig 25ms (cache hit)
82 http fetch GET 200 https://registry.npmjs.org/detective 25ms (cache hit)
83 http fetch GET 200 https://registry.npmjs.org/tmp 24ms (cache hit)
84 http fetch GET 200 https://registry.npmjs.org/arg 26ms (cache hit)
85 timing idealTree:#root Completed in 188ms
86 silly fetch manifest ts-node@>=9.0.0
87 http fetch GET 200 https://registry.npmjs.org/ts-node 2ms (cache hit)
88 silly fetch manifest @swc/core@>=1.2.50
89 http fetch GET 200 https://registry.npmjs.org/@swc%2fcore 3ms (cache hit)
90 silly fetch manifest @swc/wasm@>=1.2.50
91 http fetch GET 200 https://registry.npmjs.org/@swc%2fwasm 2ms (cache hit)
92 silly fetch manifest @types/node@*
93 http fetch GET 200 https://registry.npmjs.org/@types%2fnode 4ms (cache hit)
94 silly fetch manifest typescript@>=2.7
95 http fetch GET 200 https://registry.npmjs.org/typescript 14ms (cache hit)
96 silly placeDep ROOT arg@5.0.1 OK for: @tailwindcss/postcss7-compat@2.2.14 want: ^5.0.1
97 silly placeDep node_modules/tailwindcss chalk@4.1.2 OK for: @tailwindcss/postcss7-compat@2.2.14 want: ^4.1.2
98 silly placeDep ROOT color@4.0.1 OK for: @tailwindcss/postcss7-compat@2.2.14 want: ^4.0.1
99 silly placeDep node_modules/tailwindcss cosmiconfig@7.0.1 OK for: @tailwindcss/postcss7-compat@2.2.14 want: ^7.0.1
100 silly placeDep ROOT detective@5.2.0 OK for: @tailwindcss/postcss7-compat@2.2.14 want: ^5.2.0
101 silly placeDep ROOT didyoumean@1.2.2 OK for: @tailwindcss/postcss7-compat@2.2.14 want: ^1.2.2
102 silly placeDep ROOT dlv@1.1.3 OK for: @tailwindcss/postcss7-compat@2.2.14 want: ^1.1.3
103 silly placeDep node_modules/tailwindcss fs-extra@10.0.0 OK for: @tailwindcss/postcss7-compat@2.2.14 want: ^10.0.0
104 silly placeDep ROOT glob-parent@6.0.1 OK for: @tailwindcss/postcss7-compat@2.2.14 want: ^6.0.1
105 silly placeDep ROOT html-tags@3.1.0 OK for: @tailwindcss/postcss7-compat@2.2.14 want: ^3.1.0
106 silly placeDep ROOT is-color-stop@1.1.0 OK for: @tailwindcss/postcss7-compat@2.2.14 want: ^1.1.0
107 silly placeDep ROOT lodash.topath@4.5.2 OK for: @tailwindcss/postcss7-compat@2.2.14 want: ^4.5.2
108 silly placeDep ROOT modern-normalize@1.1.0 OK for: @tailwindcss/postcss7-compat@2.2.14 want: ^1.1.0
109 silly placeDep ROOT node-emoji@1.11.0 OK for: @tailwindcss/postcss7-compat@2.2.14 want: ^1.11.0
110 silly placeDep ROOT object-hash@2.2.0 OK for: @tailwindcss/postcss7-compat@2.2.14 want: ^2.2.0
111 silly placeDep ROOT postcss-functions@3.0.0 OK for: @tailwindcss/postcss7-compat@2.2.14 want: ^3
112 silly placeDep ROOT postcss-js@2.0.3 OK for: @tailwindcss/postcss7-compat@2.2.14 want: ^2
113 silly placeDep node_modules/tailwindcss postcss-load-config@3.1.0 OK for: @tailwindcss/postcss7-compat@2.2.14 want: ^3.1.0
114 silly placeDep ROOT postcss-nested@4.2.3 OK for: @tailwindcss/postcss7-compat@2.2.14 want: ^4
115 silly placeDep node_modules/tailwindcss postcss-value-parser@4.1.0 OK for: @tailwindcss/postcss7-compat@2.2.14 want: ^4.1.0
116 silly placeDep ROOT pretty-hrtime@1.0.3 OK for: @tailwindcss/postcss7-compat@2.2.14 want: ^1.0.3
117 silly placeDep ROOT purgecss@4.0.3 OK for: @tailwindcss/postcss7-compat@2.2.14 want: ^4.0.3
118 silly placeDep ROOT quick-lru@5.1.1 OK for: @tailwindcss/postcss7-compat@2.2.14 want: ^5.1.1
119 silly placeDep ROOT reduce-css-calc@2.1.8 OK for: @tailwindcss/postcss7-compat@2.2.14 want: ^2.1.8
120 silly placeDep ROOT tmp@0.2.1 OK for: @tailwindcss/postcss7-compat@2.2.14 want: ^0.2.1
121 silly fetch manifest ansi-styles@^4.1.0
122 silly fetch manifest supports-color@^7.1.0
123 silly fetch manifest color-convert@^2.0.1
124 silly fetch manifest color-string@^1.6.0
125 silly fetch manifest import-fresh@^3.2.1
126 silly fetch manifest parse-json@^5.0.0
127 silly fetch manifest path-type@^4.0.0
128 silly fetch manifest acorn-node@^1.6.1
129 silly fetch manifest defined@^1.0.0
130 silly fetch manifest graceful-fs@^4.2.0
131 silly fetch manifest jsonfile@^6.0.1
132 silly fetch manifest universalify@^2.0.0
133 silly fetch manifest css-color-names@^0.0.4
134 silly fetch manifest hex-color-regex@^1.1.0
135 silly fetch manifest hsl-regex@^1.0.0
136 silly fetch manifest hsla-regex@^1.0.0
137 silly fetch manifest rgb-regex@^1.0.1
138 silly fetch manifest rgba-regex@^1.0.0
139 silly fetch manifest glob@^7.1.2
140 silly fetch manifest postcss@^6.0.9
141 silly fetch manifest postcss-value-parser@^3.3.0
142 silly fetch manifest camelcase-css@^2.0.1
143 silly fetch manifest import-cwd@^3.0.0
144 silly fetch manifest lilconfig@^2.0.3
145 silly fetch manifest commander@^6.0.0
146 silly fetch manifest glob@^7.0.0
147 silly fetch manifest postcss@^8.2.1
148 silly fetch manifest css-unit-converter@^1.1.1
149 silly fetch manifest rimraf@^3.0.0
150 http fetch GET 200 https://registry.npmjs.org/hsl-regex 23ms (cache hit)
151 http fetch GET 200 https://registry.npmjs.org/jsonfile 25ms (cache hit)
152 http fetch GET 200 https://registry.npmjs.org/universalify 25ms (cache hit)
153 http fetch GET 200 https://registry.npmjs.org/acorn-node 27ms (cache hit)
154 http fetch GET 200 https://registry.npmjs.org/import-fresh 35ms (cache hit)
155 http fetch GET 200 https://registry.npmjs.org/ansi-styles 36ms (cache hit)
156 http fetch GET 200 https://registry.npmjs.org/css-color-names 25ms (cache hit)
157 http fetch GET 200 https://registry.npmjs.org/graceful-fs 27ms (cache hit)
158 http fetch GET 200 https://registry.npmjs.org/parse-json 35ms (cache hit)
159 http fetch GET 200 https://registry.npmjs.org/color-string 36ms (cache hit)
160 http fetch GET 200 https://registry.npmjs.org/rgb-regex 25ms (cache hit)
161 http fetch GET 200 https://registry.npmjs.org/color-convert 37ms (cache hit)
162 http fetch GET 200 https://registry.npmjs.org/hex-color-regex 27ms (cache hit)
163 http fetch GET 200 https://registry.npmjs.org/css-unit-converter 24ms (cache hit)
164 http fetch GET 200 https://registry.npmjs.org/commander 24ms (cache hit)
165 http fetch GET 200 https://registry.npmjs.org/supports-color 39ms (cache hit)
166 http fetch GET 200 https://registry.npmjs.org/hsla-regex 27ms (cache hit)
167 http fetch GET 200 https://registry.npmjs.org/rgba-regex 28ms (cache hit)
168 http fetch GET 200 https://registry.npmjs.org/path-type 39ms (cache hit)
169 http fetch GET 200 https://registry.npmjs.org/defined 31ms (cache hit)
170 http fetch GET 200 https://registry.npmjs.org/rimraf 27ms (cache hit)
171 http fetch GET 200 https://registry.npmjs.org/postcss 29ms (cache hit)
172 http fetch GET 200 https://registry.npmjs.org/glob 31ms (cache hit)
173 http fetch GET 200 https://registry.npmjs.org/lilconfig 30ms (cache hit)
174 http fetch GET 200 https://registry.npmjs.org/import-cwd 31ms (cache hit)
175 http fetch GET 200 https://registry.npmjs.org/camelcase-css 32ms (cache hit)
176 timing idealTree:node_modules/tailwindcss Completed in 111ms
177 timing idealTree:node_modules/arg Completed in 0ms
178 silly placeDep ROOT color-convert@2.0.1 OK for: color@4.0.1 want: ^2.0.1
179 timing idealTree Completed in 502ms
180 timing command:install Completed in 513ms
181 verbose stack TypeError: Invalid Version:
181 verbose stack     at new SemVer (/usr/local/lib/node_modules/npm/node_modules/semver/classes/semver.js:38:13)
181 verbose stack     at compare (/usr/local/lib/node_modules/npm/node_modules/semver/functions/compare.js:3:32)
181 verbose stack     at Object.gte (/usr/local/lib/node_modules/npm/node_modules/semver/functions/gte.js:2:30)
181 verbose stack     at Node.canDedupe (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1035:32)
181 verbose stack     at PlaceDep.pruneDedupable (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:419:14)
181 verbose stack     at PlaceDep.placeInTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:322:14)
181 verbose stack     at PlaceDep.place (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:211:10)
181 verbose stack     at new PlaceDep (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:68:10)
181 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:920:31
181 verbose stack     at Array.map (<anonymous>)
182 verbose cwd /Users/alexgao/Dev/chengshi-news-miniapp
183 verbose Darwin 20.6.0
184 verbose argv "/opt/homebrew/Cellar/node/16.9.1/bin/node" "/usr/local/bin/npm" "install" "-D" "tailwindcss@npm:@tailwindcss/postcss7-compat"
185 verbose node v16.9.1
186 verbose npm  v7.24.0
187 error Invalid Version:
188 verbose exit 1

**Comment by smoothdvd** [comment]
Add --legacy-bundling option to resolve this issue
