### ISSUE TITLE
Unclosed bracket when building Nextjs Ts and V3

### ISSUE THREAD

**Issue by JoseGarciaM** [tailwindlabs/tailwindcss#6323]
After upgrading and following the upgrade guide in your website I am not able to build the project.

`jcgm@JoseloG-Macbook-Pro web % npx next build                                 
info  - Checking validity of types  
info  - Creating an optimized production build  
Failed to compile.

HookWebpackError: /Users/jcgm/Dev/Horchata/web/static/css/72a5655cfa1e5d11.css:804:21: Unclosed bracket
    at makeWebpackError (/Users/jcgm/Dev/Horchata/web/node_modules/next/dist/compiled/webpack/bundle5.js:47168:9)
    at /Users/jcgm/Dev/Horchata/web/node_modules/next/dist/compiled/webpack/bundle5.js:31056:12
    at eval (eval at create (/Users/jcgm/Dev/Horchata/web/node_modules/next/dist/compiled/webpack/bundle5.js:141512:10), <anonymous>:34:1)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
-- inner error --
CssSyntaxError: /Users/jcgm/Dev/Horchata/web/static/css/72a5655cfa1e5d11.css:804:21: Unclosed bracket
    at Input.error (/Users/jcgm/Dev/Horchata/web/node_modules/next/node_modules/postcss/lib/input.js:123:16)
    at ScssParser.unclosedBracket (/Users/jcgm/Dev/Horchata/web/node_modules/next/node_modules/postcss/lib/parser.js:514:22)
    at ScssParser.other (/Users/jcgm/Dev/Horchata/web/node_modules/next/node_modules/postcss/lib/parser.js:139:35)
    at ScssParser.parse (/Users/jcgm/Dev/Horchata/web/node_modules/next/node_modules/postcss/lib/parser.js:59:16)
    at scssParse (/Users/jcgm/Dev/Horchata/web/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:335)
    at new LazyResult (/Users/jcgm/Dev/Horchata/web/node_modules/next/node_modules/postcss/lib/lazy-result.js:122:16)
    at Processor.process (/Users/jcgm/Dev/Horchata/web/node_modules/next/node_modules/postcss/lib/processor.js:33:12)
    at CssMinimizerPlugin.optimizeAsset (/Users/jcgm/Dev/Horchata/web/node_modules/next/dist/build/webpack/plugins/css-minimizer-plugin.js:43:12)
    at /Users/jcgm/Dev/Horchata/web/node_modules/next/dist/build/webpack/plugins/css-minimizer-plugin.js:77:55
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
caused by plugins in Compilation.hooks.processAssets
CssSyntaxError: /Users/jcgm/Dev/Horchata/web/static/css/72a5655cfa1e5d11.css:804:21: Unclosed bracket
    at Input.error (/Users/jcgm/Dev/Horchata/web/node_modules/next/node_modules/postcss/lib/input.js:123:16)
    at ScssParser.unclosedBracket (/Users/jcgm/Dev/Horchata/web/node_modules/next/node_modules/postcss/lib/parser.js:514:22)
    at ScssParser.other (/Users/jcgm/Dev/Horchata/web/node_modules/next/node_modules/postcss/lib/parser.js:139:35)
    at ScssParser.parse (/Users/jcgm/Dev/Horchata/web/node_modules/next/node_modules/postcss/lib/parser.js:59:16)
    at scssParse (/Users/jcgm/Dev/Horchata/web/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:335)
    at new LazyResult (/Users/jcgm/Dev/Horchata/web/node_modules/next/node_modules/postcss/lib/lazy-result.js:122:16)
    at Processor.process (/Users/jcgm/Dev/Horchata/web/node_modules/next/node_modules/postcss/lib/processor.js:33:12)
    at CssMinimizerPlugin.optimizeAsset (/Users/jcgm/Dev/Horchata/web/node_modules/next/dist/build/webpack/plugins/css-minimizer-plugin.js:43:12)
    at /Users/jcgm/Dev/Horchata/web/node_modules/next/dist/build/webpack/plugins/css-minimizer-plugin.js:77:55
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

> Build failed because of webpack errors
jcgm@JoseloG-Macbook-Pro web % `

**Comment by Divlo** [comment]
Hello! :wave:

How did you solve your issue? @JoseGarciaM 
I have a similar issue: `HookWebpackError: Missed semicolon`
