### ISSUE TITLE
TypeError: Cannot read property '700' of undefined

### ISSUE THREAD

**Issue by nasirkhan** [tailwindlabs/tailwindcss#6335]
**What version of Tailwind CSS are you using?**

^3.0.0

**What build tool (or framework if it abstracts the build tool) are you using?**

Webpack with Laravel

**What version of Node.js are you using?**

v14.15.3

**What operating system are you using?**

Windows

**Describe your issue**

I just updated Tailwind CSS to v3 and updated the related plugins. Then when i run the command `yarn dev` it throws the following error.

If i remove the `@tailwindcss/ui` from my project then the build was a success. 

```
at Object.<anonymous> (C:\wamp64\www\laravel\node_modules\@tailwindcss\ui\node_modules\@tailwindcss\typography\src\styles.js:15:40)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\wamp64\www\laravel\node_modules\@tailwindcss\ui\node_modules\@tailwindcss\typography\src\index.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at processResult (C:\wamp64\www\laravel\node_modules\webpack\lib\NormalModule.js:751:19)
    at C:\wamp64\www\laravel\node_modules\webpack\lib\NormalModule.js:853:5
    at C:\wamp64\www\laravel\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at C:\wamp64\www\laravel\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (C:\wamp64\www\laravel\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.loader (C:\wamp64\www\laravel\node_modules\postcss-loader\dist\index.js:142:7)
```

**Comment by JMedina90** [comment]
Update @tailwindcss/typography or @tailwindcss/forms to the latest version. Had the same issue and this fixed it.

**Comment by nasirkhan** [comment]
followed the update guide from https://tailwindcss.com/docs/upgrade-guide and updated the plugins as well. There is no new version found for @tailwindcss/ui

**Comment by keithbrink** [comment]
You shouldn't be using tailwindcss/ui, since Tailwind 2.0: https://tailwindui.com/changes-for-v2#tailwindcss-ui-is-no-longer-needed

If you update to use the plugins directly rather than @tailwindcss/ui you should be good.

**Comment by pgarzina** [comment]
Hello,

we are experiencing the same issue as of today.

If someone could please give me a better understanding as to why the issue started to appear (our app stopped compiling).
The thing is we have not introduced code changes or version changes (our package.json/lock has not been changed) but the app broke down. 

We are using Angular, and updating to Tailwind 3.00 solves the issue. But what bugs me is that we have a CI/CD pipeline and all the past builds passed and now suddenly without any code changes the build started failing.

Thanks

**Comment by nasirkhan** [comment]
@keithbrink Thanks. 

I mentioned in my first post that removing tailwindcss/ui solves that issue. We were checking if anything breaks if we remove it from the project. 

As per UI doc (https://tailwindui.com/changes-for-v2#tailwindcss-ui-is-no-longer-needed) we removed it from our project.

**Comment by 22289d** [comment]
Had the same issue and updating Typography and Forms plugins fixed it.

**Comment by sirvine** [comment]
I had to uninstall Typography and reinstall with `npm install -D @tailwindcss/typography@next` to fix this. See https://github.com/tailwindlabs/tailwindcss-typography/issues/214#issuecomment-974837275

**Comment by haseebeqx** [comment]
I had to patch the latest `src/public/colors.js`.
