### ISSUE TITLE
utilities class inset-0 build error within vite

### ISSUE THREAD

**Issue by ByteJitter** [tailwindlabs/tailwindcss#6807]
**What version of Tailwind CSS are you using?**

3.0.7

**What build tool (or framework if it abstracts the build tool) are you using?**

"@vitejs/plugin-vue": "^1.2.3",
"@vue/babel-plugin-jsx": "^1.0.6",
"@vue/compiler-sfc": "^3.0.5",
"babel-plugin-import": "^1.13.3",
"postcss-px-to-viewport": "^1.1.1",
"vite": "^2.3.7",
"vite-plugin-style-import": "^1.0.0"

**What version of Node.js are you using?**
v14.17.3

**What browser are you using?**
Chrome 96.0.4664.110

**What operating system are you using?**
windows 10

**Describe your issue**

when i coding with the following:
```
@tailwind components;

@layer components {
  .border-solid-fff {
    @apply border border-solid border-#fff;
  }
  // .bottom-btn-wrapper {
  //   @apply fixed inset-0 top-auto h-2.4 flex justify-around items-center box-content shadow-s1 bg-#fff px-0.64 pb-constant-area-inset-bottom pb-env-area-inset-bottom z-98;
  // }

  .bottom-btn-wrapper {
    @apply fixed inset-0;
  }
}
```
then i input `npm run dev`  within powershell, the errors appear,
```
[vite] Internal server error: Cannot read property 'length' of undefined
      at posToNumber (E:\jd-express-welfare\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:4213:27)
      at generateCodeFrame (E:\jd-express-welfare\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:4238:13)
      at formatError (E:\jd-express-welfare\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:44604:42)
      at TransformContext.error (E:\jd-express-welfare\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:44560:19)
      at Object.transform (E:\jd-express-welfare\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:44768:25)
      at async transformRequest (E:\jd-express-welfare\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:59029:29)
      at async viteTransformMiddleware (E:\jd-express-welfare\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:59167:32)
```

when i use `inset-x-0`、`inset-y-0` in vite，there is errors above appear.
Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead.

**Comment by adamwathan** [comment]
Hey! Can't reproduce, this works for me in a Vite project. You do have some invalid stuff in your code sample though, for example you can't use `//` style comments in CSS, and `border-#fff` isn't a class in Tailwind by default.

Going to close since I can't reproduce but feel free to open a new issue that includes a proper reproduction if still a problem — it's a required field as mentioned in the issue template.
