### ISSUE TITLE
Adding typography breaks the build: Cannot read property '700' of undefined

### ISSUE THREAD

**Issue by dstpierre** [tailwindlabs/tailwindcss#6855]
**What version of Tailwind CSS are you using?**
```
"@tailwindcss/aspect-ratio": "^0.2.0",
"@tailwindcss/forms": "^0.2.1",
"@tailwindcss/typography": "^0.5.0",
"autoprefixer": "^10.2.5",
"postcss": "^8.2.8",
"tailwindcss": "^2.0.3"
```
So v2.0.3

**What build tool (or framework if it abstracts the build tool) are you using?**

`tailwindcss build -i styles.css -o ./static/css/style.css`

**What version of Node.js are you using?**

v14.15.4

**What operating system are you using?**

Linux, Debian 10

**Reproduction / Describe your issue****

Just added `@tailwindcss/typography` from a TailwindUI requested, here's the `plugins` section of the `tailwind.config.js`

```
plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/typography"),
    require("@tailwindcss/aspect-ratio")
  ],
```

Removing the `typography` plugin fixes the issue.

This is the error stack trace:

```
(node:16219) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '700' of undefined
    at Object.<anonymous> (path/node_modules/@tailwindcss/typography/src/styles.js:949:38)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (path/node_modules/@tailwindcss/typography/src/index.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

```

Any help / pointer highly appreciated.
Thanks

**Comment by adamwathan** [comment]
Hey! If you are using Tailwind CSS v2, you'll want to use v0.4 of the typography plugin. v0.5 is the latest release and depends on Tailwind CSS v3.

You can install v0.4 like this:

```
npm install -D @tailwindcss/typography@^0.4
```

**Comment by dstpierre** [comment]
thanks Adam, I appreciate, it works. Just in between v2 to v3 update (as in, I've not yet look into migrating and if there's any breaking changes re: Tailwind UI etc).
