### ISSUE TITLE
Unable to run CLI, access error for something it really shouldn't be accessing

### ISSUE THREAD

**Issue by Lancelotbronner** [tailwindlabs/tailwindcss#9019]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/9005

<div type='discussions-op-text'>

<sup>Originally posted by **Lancelotbronner** August  1, 2022</sup>
On running the following command (on macOS):

```console
npx tailwindcss -i tailwind.src.css -o wwwroot/css/tailwind.out.css
```

With the following `package.json`:

```json
{
  "devDependencies": {
    "tailwindcss": "^3.1.7"
  }
}
```

I get the following error, the CLI cannot access my backup drive, something it really shouldn't be trying to scan.

```
node:fs:1450
  handleErrorFromBinding(ctx);
  ^

Error: EACCES: permission denied, scandir '/Volumes/MyBackupDrive'
    at Object.readdirSync (node:fs:1450:3)
    at readdirWithFileTypes (/[redacted]/node_modules/@nodelib/fs.scandir/out/providers/sync.js:16:33)
    at Object.read (/[redacted]/node_modules/@nodelib/fs.scandir/out/providers/sync.js:10:16)
    at SyncReader.scandirSync [as _scandir] (/[redacted]/node_modules/@nodelib/fs.scandir/out/index.js:18:17)
    at SyncReader._handleDirectory (/[redacted]/node_modules/@nodelib/fs.walk/out/readers/sync.js:28:34)
    at SyncReader._handleQueue (/[redacted]/node_modules/@nodelib/fs.walk/out/readers/sync.js:23:18)
    at SyncReader.read (/[redacted]/node_modules/@nodelib/fs.walk/out/readers/sync.js:15:14)
    at SyncProvider.read (/[redacted]/node_modules/@nodelib/fs.walk/out/providers/sync.js:11:29)
    at ReaderSync.walkSync [as _walkSync] (/[redacted]/node_modules/@nodelib/fs.walk/out/index.js:20:21)
    at ReaderSync.dynamic (/[redacted]/node_modules/fast-glob/out/readers/sync.js:13:21) {
  errno: -13,
  syscall: 'scandir',
  code: 'EACCES',
  path: '/Volumes/MyBackupDrive'
}

Node.js v18.4.0
```</div>

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction — a [Tailwind Play](https://play.tailwindcss.com) if the issue can be reproduced there, or a GitHub repository where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!

If I would make a guess, my guess would be that one of the files matched in your `content` section of your `tailwind.config.js` is a symlink to a file inside `/Volumes/MyBackupDrive`.
