### ISSUE TITLE
Install Tailwindcss using Rails framework on OpenBSD system

### ISSUE THREAD

**Issue by wesley974** [tailwindlabs/tailwindcss#9642]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/9636

<div type='discussions-op-text'>

<sup>Originally posted by **wesley974** October 22, 2022</sup>
Hello,

I use OpenBSD 7.2 with ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-openbsd] and Rails 7.0.4.

When I try this: 
`rails new rails new my-app --css tailwind`

I get the following error:
```
Compile initial Tailwind build
         run  rails tailwindcss:build from "."
rails aborted!
Tailwindcss::Commands::UnsupportedPlatformException: tailwindcss-rails does not support the x86_64-openbsd platform
Please install tailwindcss following instructions at https://tailwindcss.com/docs/installation

Tasks: TOP => tailwindcss:build
(See full trace by running task with --trace)
openbsd$ rails tailwindcss:build
```

Trying `rails tailwindcss:build --trace` give me:
```
** Invoke tailwindcss:build (first_time)
** Execute tailwindcss:build
rails aborted!
Tailwindcss::Commands::UnsupportedPlatformException: tailwindcss-rails does not support the x86_64-openbsd platform
Please install tailwindcss following instructions at https://tailwindcss.com/docs/installation
/home/wesley/.bundle/ruby/3.1/gems/tailwindcss-rails-2.0.16/lib/tailwindcss/commands.rb:22:in `executable'
/home/wesley/.bundle/ruby/3.1/gems/tailwindcss-rails-2.0.16/lib/tailwindcss/commands.rb:60:in `compile_command'
/home/wesley/.bundle/ruby/3.1/gems/tailwindcss-rails-2.0.16/lib/tasks/build.rake:5:in `block (2 levels) in <main>'
/home/wesley/.bundle/ruby/3.1/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/home/wesley/.bundle/ruby/3.1/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/home/wesley/.bundle/ruby/3.1/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/home/wesley/.bundle/ruby/3.1/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/wesley/.bundle/ruby/3.1/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/home/wesley/.bundle/ruby/3.1/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/wesley/.bundle/ruby/3.1/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/home/wesley/.bundle/ruby/3.1/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/home/wesley/.bundle/ruby/3.1/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/wesley/.bundle/ruby/3.1/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/home/wesley/.bundle/ruby/3.1/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/home/wesley/.bundle/ruby/3.1/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/home/wesley/.bundle/ruby/3.1/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/home/wesley/.bundle/ruby/3.1/gems/railties-7.0.4/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/home/wesley/.bundle/ruby/3.1/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/home/wesley/.bundle/ruby/3.1/gems/railties-7.0.4/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/home/wesley/.bundle/ruby/3.1/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/home/wesley/.bundle/ruby/3.1/gems/railties-7.0.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/wesley/.bundle/ruby/3.1/gems/railties-7.0.4/lib/rails/command.rb:51:in `invoke'
/home/wesley/.bundle/ruby/3.1/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<main>'
/home/wesley/.bundle/ruby/3.1/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/wesley/.bundle/ruby/3.1/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => tailwindcss:build
```

Anyone can help me to get it working?

Thank you very much.

Cheers,

/Wesley

</div>

**Comment by reinink** [comment]
Hey! 👋

So I'm no linux or Rails expert, but from reading through the [Tailwind CSS for Rails](https://github.com/rails/tailwindcss-rails) source the issue here is that we don't provide an `x86_64-openbsd` binary for Tailwind CSS. Here are the binaries we support at this time:

- `tailwindcss-linux-arm64`
- `tailwindcss-linux-armv7`
- `tailwindcss-linux-x64`
- `tailwindcss-macos-arm64`
- `tailwindcss-macos-x64`
- `tailwindcss-windows-x64.exe`

From what I can tell, [pkg](https://github.com/vercel/pkg), the tool we use to package up Tailwind CSS into executables, doesn't have support for OpenBSD. I suspect that's because Node.js itself doesn't test or compile binaries for OpenBSD. Given that, it's unlikely that we're going to be able to add support for this platform.

One thing you could try is manually specifying an OpenBSD-compatible platform ([as suggested](https://github.com/rails/tailwindcss-rails#error-cannot-find-the-tailwindcss-executable-for-supported-platform) in the tailwindcss-rails docs):

```sh
bundle lock --add-platform <platform-name>
```

However, I'm not convinced that any of the binaries we provide are actually OpenBSD-compatible, so that might be a dead end.

Given all that, I'd just recommend just installing Tailwind CSS the "normal" way: https://tailwindcss.com/docs/installation

Hope that helps 👍

**Comment by wesley974** [comment]
Merci!
I will go with the cdn.
