### ISSUE TITLE
vite & @tailwindcss/forms & customization fail to work

### ISSUE THREAD

**Issue by sysmat** [tailwindlabs/tailwindcss#9709]
**What version of Tailwind CSS are you using?**

```
"@tailwindcss/forms": "^0.5.3",
    "autoprefixer": "^10.4.13",
    "postcss": "^8.4.18",
    "tailwindcss": "^3.2.1",
"vite": "^3.2.2",
    "vite-plugin-solid": "^2.3.10",

```
**What build tool (or framework if it abstracts the build tool) are you using?**

```
"vite": "^3.2.2",
"vite-plugin-solid": "^2.3.10",
"solid-js": "^1.6.1"
```

**What version of Node.js are you using?**

```
$ node -v
v16.15.1

```
**What browser are you using?**

- Chrome, 

**What operating system are you using?**

- OS:  Windows

**Reproduction URL**

- https://stackblitz.com/edit/solidjs-templates-2f1par?file=package.json

**Describe your issue**

```
10:32:20 AM [vite] Internal server error: [postcss] /home/projects/solidjs-templates-2f1par/src/index.css:1:1: The `focus:` class does not exist. If `focus:` is a custom class, make sure it is defined within a `@layer` directive.
  Plugin: vite:css
  File: /home/projects/solidjs-templates-2f1par/src/index.css:1:1
  1  |  @tailwind base;
     |   ^
  2  |  @tailwind components;
  3  |  @tailwind utilities;
      at Input.error (/home/projects/solidjs-templates-2f1par/node_modules/postcss/lib/input.js:148:16)
      at AtRule.error (/home/projects/solidjs-templates-2f1par/node_modules/postcss/lib/node.js:60:32)
      at processApply (/home/projects/solidjs-templates-2f1par/node_modules/tailwindcss/lib/lib/expandApplyAtRules.js:357:29)
      at eval (/home/projects/solidjs-templates-2f1par/node_modules/tailwindcss/lib/lib/expandApplyAtRules.js:505:9)
      at eval (/home/projects/solidjs-templates-2f1par/node_modules/tailwindcss/lib/processTailwindFeatures.js:55:50)
      at plugins (/home/projects/solidjs-templates-2f1par/node_modules/tailwindcss/lib/index.js:38:63)
      at LazyResult.runOnRoot (/home/projects/solidjs-templates-2f1par/node_modules/postcss/lib/lazy-result.js:339:16)
      at LazyResult.runAsync (/home/projects/solidjs-templates-2f1par/node_modules/postcss/lib/lazy-result.js:393:26)
      at LazyResult.async (/home/projects/solidjs-templates-2f1par/node_modules/postcss/lib/lazy-result.js:221:30)
      at LazyResult.then (/home/projects/solidjs-templates-2f1par/node_modules/postcss/lib/lazy-result.js:206:17)

```

**Comment by sysmat** [comment]
- It seams VSC formatting was problem, when save it add space after `focus:`
- tooling should handle trimming, but this small space error was the problem

**Comment by melaniecarr23** [comment]
I'm getting something similar.  I tried downgrading tailwind to a lower version, and that didn't fix it.  As soon as I comment out require('@tailwindcss/forms') in my tailwind.config.js plugins array, the error goes away.
```
 [vite] Internal server error: Cannot read properties of undefined (reading 'length')
      at memoizedBinarySearch (file:///home/melaniecarr/Documents/Websites/ihcdocdash/node_modules/vite/dist/node/chunks/dep-2faf2534.js:9948:25)
      at traceSegmentInternal (file:///home/melaniecarr/Documents/Websites/ihcdocdash/node_modules/vite/dist/node/chunks/dep-2faf2534.js:10055:17)
      at originalPositionFor$1 (file:///home/melaniecarr/Documents/Websites/ihcdocdash/node_modules/vite/dist/node/chunks/dep-2faf2534.js:10041:23)
      at formatError (file:///home/melaniecarr/Documents/Websites/ihcdocdash/node_modules/vite/dist/node/chunks/dep-2faf2534.js:40420:54)
      at TransformContext.error (file:///home/melaniecarr/Documents/Websites/ihcdocdash/node_modules/vite/dist/node/chunks/dep-2faf2534.js:40354:19)
      at Object.transform (file:///home/melaniecarr/Documents/Websites/ihcdocdash/node_modules/vite/dist/node/chunks/dep-2faf2534.js:40614:25)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file:///home/melaniecarr/Documents/Websites/ihcdocdash/node_modules/vite/dist/node/chunks/dep-2faf2534.js:36998:29)
8:17:18 PM [vite] Internal server error: Cannot read properties of undefined (reading 'length')
      at memoizedBinarySearch (file:///home/melaniecarr/Documents/Websites/ihcdocdash/node_modules/vite/dist/node/chunks/dep-2faf2534.js:9948:25)
      at traceSegmentInternal (file:///home/melaniecarr/Documents/Websites/ihcdocdash/node_modules/vite/dist/node/chunks/dep-2faf2534.js:10055:17)
      at originalPositionFor$1 (file:///home/melaniecarr/Documents/Websites/ihcdocdash/node_modules/vite/dist/node/chunks/dep-2faf2534.js:10041:23)
      at formatError (file:///home/melaniecarr/Documents/Websites/ihcdocdash/node_modules/vite/dist/node/chunks/dep-2faf2534.js:40420:54)
      at TransformContext.error (file:///home/melaniecarr/Documents/Websites/ihcdocdash/node_modules/vite/dist/node/chunks/dep-2faf2534.js:40354:19)
      at Object.transform (file:///home/melaniecarr/Documents/Websites/ihcdocdash/node_modules/vite/dist/node/chunks/dep-2faf2534.js:40614:25)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file:///home/melaniecarr/Documents/Websites/ihcdocdash/node_modules/vite/dist/node/chunks/dep-2faf2534.js:36998:29) (x2)

```

I'm using all the latest versions of tailwind, vite, vue, and tailwindforms, as well as nodejs.  chrome is my browser.
